// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: node_tunnel.proto

package nodetunnelv1

import (
	v1 "deeppool/libs/proto/llm/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientMessage_Register
	//	*ClientMessage_Heartbeat
	//	*ClientMessage_TaskResult
	//	*ClientMessage_TaskChunk
	//	*ClientMessage_UpdateModels
	//	*ClientMessage_ErrorLog
	Payload       isClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_node_tunnel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_node_tunnel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_node_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMessage) GetPayload() isClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientMessage) GetRegister() *RegisterRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *ClientMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ClientMessage) GetTaskResult() *TaskResult {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_TaskResult); ok {
			return x.TaskResult
		}
	}
	return nil
}

func (x *ClientMessage) GetTaskChunk() *TaskStreamChunk {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_TaskChunk); ok {
			return x.TaskChunk
		}
	}
	return nil
}

func (x *ClientMessage) GetUpdateModels() *UpdateModelsNotify {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_UpdateModels); ok {
			return x.UpdateModels
		}
	}
	return nil
}

func (x *ClientMessage) GetErrorLog() *ErrorLogReport {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_ErrorLog); ok {
			return x.ErrorLog
		}
	}
	return nil
}

type isClientMessage_Payload interface {
	isClientMessage_Payload()
}

type ClientMessage_Register struct {
	// 连接建立后首条消息：鉴权注册
	Register *RegisterRequest `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type ClientMessage_Heartbeat struct {
	// 心跳响应（回复服务端 ping）
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type ClientMessage_TaskResult struct {
	// 推理任务结果（非流式，单次完整返回）
	TaskResult *TaskResult `protobuf:"bytes,3,opt,name=task_result,json=taskResult,proto3,oneof"`
}

type ClientMessage_TaskChunk struct {
	// 推理任务流式 chunk
	TaskChunk *TaskStreamChunk `protobuf:"bytes,4,opt,name=task_chunk,json=taskChunk,proto3,oneof"`
}

type ClientMessage_UpdateModels struct {
	// 模型列表变更通知（重载完成后客户端主动上报）
	UpdateModels *UpdateModelsNotify `protobuf:"bytes,5,opt,name=update_models,json=updateModels,proto3,oneof"`
}

type ClientMessage_ErrorLog struct {
	// 客户端 ERROR 日志批量上报
	ErrorLog *ErrorLogReport `protobuf:"bytes,6,opt,name=error_log,json=errorLog,proto3,oneof"`
}

func (*ClientMessage_Register) isClientMessage_Payload() {}

func (*ClientMessage_Heartbeat) isClientMessage_Payload() {}

func (*ClientMessage_TaskResult) isClientMessage_Payload() {}

func (*ClientMessage_TaskChunk) isClientMessage_Payload() {}

func (*ClientMessage_UpdateModels) isClientMessage_Payload() {}

func (*ClientMessage_ErrorLog) isClientMessage_Payload() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_RegisterAck
	//	*ServerMessage_Heartbeat
	//	*ServerMessage_InferenceTask
	//	*ServerMessage_TaskCancel
	//	*ServerMessage_ReloadModels
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_node_tunnel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_node_tunnel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_node_tunnel_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetRegisterAck() *RegisterResponse {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_RegisterAck); ok {
			return x.RegisterAck
		}
	}
	return nil
}

func (x *ServerMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ServerMessage) GetInferenceTask() *InferenceTask {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_InferenceTask); ok {
			return x.InferenceTask
		}
	}
	return nil
}

func (x *ServerMessage) GetTaskCancel() *TaskCancel {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_TaskCancel); ok {
			return x.TaskCancel
		}
	}
	return nil
}

func (x *ServerMessage) GetReloadModels() *ReloadModelsCommand {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_ReloadModels); ok {
			return x.ReloadModels
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_RegisterAck struct {
	// 注册响应
	RegisterAck *RegisterResponse `protobuf:"bytes,1,opt,name=register_ack,json=registerAck,proto3,oneof"`
}

type ServerMessage_Heartbeat struct {
	// 心跳（服务端 ping）
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type ServerMessage_InferenceTask struct {
	// 下发推理任务
	InferenceTask *InferenceTask `protobuf:"bytes,3,opt,name=inference_task,json=inferenceTask,proto3,oneof"`
}

type ServerMessage_TaskCancel struct {
	// 取消正在执行的任务
	TaskCancel *TaskCancel `protobuf:"bytes,4,opt,name=task_cancel,json=taskCancel,proto3,oneof"`
}

type ServerMessage_ReloadModels struct {
	// 模型重载指令（管理员调整模型分配后触发）
	ReloadModels *ReloadModelsCommand `protobuf:"bytes,5,opt,name=reload_models,json=reloadModels,proto3,oneof"`
}

func (*ServerMessage_RegisterAck) isServerMessage_Payload() {}

func (*ServerMessage_Heartbeat) isServerMessage_Payload() {}

func (*ServerMessage_InferenceTask) isServerMessage_Payload() {}

func (*ServerMessage_TaskCancel) isServerMessage_Payload() {}

func (*ServerMessage_ReloadModels) isServerMessage_Payload() {}

type ReloadModelsCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 触发原因（供日志追踪）
	Reason        string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadModelsCommand) Reset() {
	*x = ReloadModelsCommand{}
	mi := &file_node_tunnel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadModelsCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadModelsCommand) ProtoMessage() {}

func (x *ReloadModelsCommand) ProtoReflect() protoreflect.Message {
	mi := &file_node_tunnel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadModelsCommand.ProtoReflect.Descriptor instead.
func (*ReloadModelsCommand) Descriptor() ([]byte, []int) {
	return file_node_tunnel_proto_rawDescGZIP(), []int{2}
}

func (x *ReloadModelsCommand) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type UpdateModelsNotify struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 设备当前支持的所有模型名称列表
	ModelNames    []string `protobuf:"bytes,1,rep,name=model_names,json=modelNames,proto3" json:"model_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateModelsNotify) Reset() {
	*x = UpdateModelsNotify{}
	mi := &file_node_tunnel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateModelsNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateModelsNotify) ProtoMessage() {}

func (x *UpdateModelsNotify) ProtoReflect() protoreflect.Message {
	mi := &file_node_tunnel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateModelsNotify.ProtoReflect.Descriptor instead.
func (*UpdateModelsNotify) Descriptor() ([]byte, []int) {
	return file_node_tunnel_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateModelsNotify) GetModelNames() []string {
	if x != nil {
		return x.ModelNames
	}
	return nil
}

type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 设备唯一标识
	Simei string `protobuf:"bytes,1,opt,name=simei,proto3" json:"simei,omitempty"`
	// 鉴权令牌（由 manager 颁发的 session token）
	AuthToken string `protobuf:"bytes,2,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	// 当前运行的模型名称（兼容旧客户端，新客户端应使用 model_names）
	ModelName string `protobuf:"bytes,3,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	// 设备本地推理引擎类型（vllm_mlx / vllm / llamacpp）
	Engine string `protobuf:"bytes,4,opt,name=engine,proto3" json:"engine,omitempty"`
	// 设备支持的所有模型名称列表（多模型场景）
	ModelNames    []string `protobuf:"bytes,5,rep,name=model_names,json=modelNames,proto3" json:"model_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_node_tunnel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_tunnel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_node_tunnel_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterRequest) GetSimei() string {
	if x != nil {
		return x.Simei
	}
	return ""
}

func (x *RegisterRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *RegisterRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *RegisterRequest) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *RegisterRequest) GetModelNames() []string {
	if x != nil {
		return x.ModelNames
	}
	return nil
}

type RegisterResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// 服务端分配的会话 ID，后续消息引用
	SessionId string `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// 建议的心跳间隔（秒）
	HeartbeatIntervalSec int32 `protobuf:"varint,4,opt,name=heartbeat_interval_sec,json=heartbeatIntervalSec,proto3" json:"heartbeat_interval_sec,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_node_tunnel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_tunnel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_node_tunnel_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RegisterResponse) GetHeartbeatIntervalSec() int32 {
	if x != nil {
		return x.HeartbeatIntervalSec
	}
	return 0
}

type Heartbeat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 时间戳（毫秒），用于计算 RTT
	TimestampMs   int64 `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_node_tunnel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_node_tunnel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_node_tunnel_proto_rawDescGZIP(), []int{6}
}

func (x *Heartbeat) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type InferenceTask struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 全局唯一任务 ID，用于追踪与取消
	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// 是否流式返回
	Stream bool `protobuf:"varint,2,opt,name=stream,proto3" json:"stream,omitempty"`
	// 推理请求体，复用 llm_infer.proto 的完整请求结构
	Request       *v1.ChatCompletionRequest `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferenceTask) Reset() {
	*x = InferenceTask{}
	mi := &file_node_tunnel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferenceTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceTask) ProtoMessage() {}

func (x *InferenceTask) ProtoReflect() protoreflect.Message {
	mi := &file_node_tunnel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceTask.ProtoReflect.Descriptor instead.
func (*InferenceTask) Descriptor() ([]byte, []int) {
	return file_node_tunnel_proto_rawDescGZIP(), []int{7}
}

func (x *InferenceTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *InferenceTask) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

func (x *InferenceTask) GetRequest() *v1.ChatCompletionRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type TaskResult struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	TaskId  string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Success bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	// 错误信息（仅 success=false 时有值）
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// 完整推理结果，复用 llm_infer.proto 响应结构
	Response      *v1.ChatCompletionResponse `protobuf:"bytes,4,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_node_tunnel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_node_tunnel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_node_tunnel_proto_rawDescGZIP(), []int{8}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TaskResult) GetResponse() *v1.ChatCompletionResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

type TaskStreamChunk struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	TaskId  string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Success bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error   string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// 流式 chunk，复用 llm_infer.proto chunk 结构
	Chunk *v1.ChatCompletionChunk `protobuf:"bytes,4,opt,name=chunk,proto3" json:"chunk,omitempty"`
	// 是否为最后一个 chunk（标记流结束）
	Done          bool `protobuf:"varint,5,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStreamChunk) Reset() {
	*x = TaskStreamChunk{}
	mi := &file_node_tunnel_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStreamChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStreamChunk) ProtoMessage() {}

func (x *TaskStreamChunk) ProtoReflect() protoreflect.Message {
	mi := &file_node_tunnel_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStreamChunk.ProtoReflect.Descriptor instead.
func (*TaskStreamChunk) Descriptor() ([]byte, []int) {
	return file_node_tunnel_proto_rawDescGZIP(), []int{9}
}

func (x *TaskStreamChunk) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskStreamChunk) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskStreamChunk) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TaskStreamChunk) GetChunk() *v1.ChatCompletionChunk {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *TaskStreamChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type TaskCancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskCancel) Reset() {
	*x = TaskCancel{}
	mi := &file_node_tunnel_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCancel) ProtoMessage() {}

func (x *TaskCancel) ProtoReflect() protoreflect.Message {
	mi := &file_node_tunnel_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCancel.ProtoReflect.Descriptor instead.
func (*TaskCancel) Descriptor() ([]byte, []int) {
	return file_node_tunnel_proto_rawDescGZIP(), []int{10}
}

func (x *TaskCancel) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskCancel) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// ErrorLogEntry 单条错误日志条目。
type ErrorLogEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 日志级别：ERROR / CRITICAL
	Level string `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	// Python logger 名称（模块路径，如 engine.vllm_mlx）
	LoggerName string `protobuf:"bytes,2,opt,name=logger_name,json=loggerName,proto3" json:"logger_name,omitempty"`
	// 错误消息（客户端截断至 4KB）
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// 堆栈信息（客户端截断至 8KB）
	Traceback string `protobuf:"bytes,4,opt,name=traceback,proto3" json:"traceback,omitempty"`
	// 客户端时间戳（毫秒）
	TimestampMs   int64 `protobuf:"varint,5,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorLogEntry) Reset() {
	*x = ErrorLogEntry{}
	mi := &file_node_tunnel_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorLogEntry) ProtoMessage() {}

func (x *ErrorLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_node_tunnel_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorLogEntry.ProtoReflect.Descriptor instead.
func (*ErrorLogEntry) Descriptor() ([]byte, []int) {
	return file_node_tunnel_proto_rawDescGZIP(), []int{11}
}

func (x *ErrorLogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *ErrorLogEntry) GetLoggerName() string {
	if x != nil {
		return x.LoggerName
	}
	return ""
}

func (x *ErrorLogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorLogEntry) GetTraceback() string {
	if x != nil {
		return x.Traceback
	}
	return ""
}

func (x *ErrorLogEntry) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

// ErrorLogReport 批量错误日志上报。
type ErrorLogReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*ErrorLogEntry       `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorLogReport) Reset() {
	*x = ErrorLogReport{}
	mi := &file_node_tunnel_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorLogReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorLogReport) ProtoMessage() {}

func (x *ErrorLogReport) ProtoReflect() protoreflect.Message {
	mi := &file_node_tunnel_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorLogReport.ProtoReflect.Descriptor instead.
func (*ErrorLogReport) Descriptor() ([]byte, []int) {
	return file_node_tunnel_proto_rawDescGZIP(), []int{12}
}

func (x *ErrorLogReport) GetEntries() []*ErrorLogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_node_tunnel_proto protoreflect.FileDescriptor

const file_node_tunnel_proto_rawDesc = "" +
	"\n" +
	"\x11node_tunnel.proto\x12\x16deeppool.nodetunnel.v1\x1a\x0fllm_infer.proto\"\xcf\x03\n" +
	"\rClientMessage\x12E\n" +
	"\bregister\x18\x01 \x01(\v2'.deeppool.nodetunnel.v1.RegisterRequestH\x00R\bregister\x12A\n" +
	"\theartbeat\x18\x02 \x01(\v2!.deeppool.nodetunnel.v1.HeartbeatH\x00R\theartbeat\x12E\n" +
	"\vtask_result\x18\x03 \x01(\v2\".deeppool.nodetunnel.v1.TaskResultH\x00R\n" +
	"taskResult\x12H\n" +
	"\n" +
	"task_chunk\x18\x04 \x01(\v2'.deeppool.nodetunnel.v1.TaskStreamChunkH\x00R\ttaskChunk\x12Q\n" +
	"\rupdate_models\x18\x05 \x01(\v2*.deeppool.nodetunnel.v1.UpdateModelsNotifyH\x00R\fupdateModels\x12E\n" +
	"\terror_log\x18\x06 \x01(\v2&.deeppool.nodetunnel.v1.ErrorLogReportH\x00R\berrorLogB\t\n" +
	"\apayload\"\x97\x03\n" +
	"\rServerMessage\x12M\n" +
	"\fregister_ack\x18\x01 \x01(\v2(.deeppool.nodetunnel.v1.RegisterResponseH\x00R\vregisterAck\x12A\n" +
	"\theartbeat\x18\x02 \x01(\v2!.deeppool.nodetunnel.v1.HeartbeatH\x00R\theartbeat\x12N\n" +
	"\x0einference_task\x18\x03 \x01(\v2%.deeppool.nodetunnel.v1.InferenceTaskH\x00R\rinferenceTask\x12E\n" +
	"\vtask_cancel\x18\x04 \x01(\v2\".deeppool.nodetunnel.v1.TaskCancelH\x00R\n" +
	"taskCancel\x12R\n" +
	"\rreload_models\x18\x05 \x01(\v2+.deeppool.nodetunnel.v1.ReloadModelsCommandH\x00R\freloadModelsB\t\n" +
	"\apayload\"-\n" +
	"\x13ReloadModelsCommand\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"5\n" +
	"\x12UpdateModelsNotify\x12\x1f\n" +
	"\vmodel_names\x18\x01 \x03(\tR\n" +
	"modelNames\"\x9e\x01\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05simei\x18\x01 \x01(\tR\x05simei\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x02 \x01(\tR\tauthToken\x12\x1d\n" +
	"\n" +
	"model_name\x18\x03 \x01(\tR\tmodelName\x12\x16\n" +
	"\x06engine\x18\x04 \x01(\tR\x06engine\x12\x1f\n" +
	"\vmodel_names\x18\x05 \x03(\tR\n" +
	"modelNames\"\x9b\x01\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x124\n" +
	"\x16heartbeat_interval_sec\x18\x04 \x01(\x05R\x14heartbeatIntervalSec\".\n" +
	"\tHeartbeat\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\"\x82\x01\n" +
	"\rInferenceTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06stream\x18\x02 \x01(\bR\x06stream\x12@\n" +
	"\arequest\x18\x03 \x01(\v2&.deeppool.llm.v1.ChatCompletionRequestR\arequest\"\x9a\x01\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12C\n" +
	"\bresponse\x18\x04 \x01(\v2'.deeppool.llm.v1.ChatCompletionResponseR\bresponse\"\xaa\x01\n" +
	"\x0fTaskStreamChunk\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12:\n" +
	"\x05chunk\x18\x04 \x01(\v2$.deeppool.llm.v1.ChatCompletionChunkR\x05chunk\x12\x12\n" +
	"\x04done\x18\x05 \x01(\bR\x04done\"=\n" +
	"\n" +
	"TaskCancel\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xa1\x01\n" +
	"\rErrorLogEntry\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x1f\n" +
	"\vlogger_name\x18\x02 \x01(\tR\n" +
	"loggerName\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\ttraceback\x18\x04 \x01(\tR\ttraceback\x12!\n" +
	"\ftimestamp_ms\x18\x05 \x01(\x03R\vtimestampMs\"Q\n" +
	"\x0eErrorLogReport\x12?\n" +
	"\aentries\x18\x01 \x03(\v2%.deeppool.nodetunnel.v1.ErrorLogEntryR\aentries2o\n" +
	"\x11NodeTunnelService\x12Z\n" +
	"\x06Tunnel\x12%.deeppool.nodetunnel.v1.ClientMessage\x1a%.deeppool.nodetunnel.v1.ServerMessage(\x010\x01B0Z.deeppool/libs/proto/nodetunnel/v1;nodetunnelv1b\x06proto3"

var (
	file_node_tunnel_proto_rawDescOnce sync.Once
	file_node_tunnel_proto_rawDescData []byte
)

func file_node_tunnel_proto_rawDescGZIP() []byte {
	file_node_tunnel_proto_rawDescOnce.Do(func() {
		file_node_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_tunnel_proto_rawDesc), len(file_node_tunnel_proto_rawDesc)))
	})
	return file_node_tunnel_proto_rawDescData
}

var file_node_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_node_tunnel_proto_goTypes = []any{
	(*ClientMessage)(nil),             // 0: deeppool.nodetunnel.v1.ClientMessage
	(*ServerMessage)(nil),             // 1: deeppool.nodetunnel.v1.ServerMessage
	(*ReloadModelsCommand)(nil),       // 2: deeppool.nodetunnel.v1.ReloadModelsCommand
	(*UpdateModelsNotify)(nil),        // 3: deeppool.nodetunnel.v1.UpdateModelsNotify
	(*RegisterRequest)(nil),           // 4: deeppool.nodetunnel.v1.RegisterRequest
	(*RegisterResponse)(nil),          // 5: deeppool.nodetunnel.v1.RegisterResponse
	(*Heartbeat)(nil),                 // 6: deeppool.nodetunnel.v1.Heartbeat
	(*InferenceTask)(nil),             // 7: deeppool.nodetunnel.v1.InferenceTask
	(*TaskResult)(nil),                // 8: deeppool.nodetunnel.v1.TaskResult
	(*TaskStreamChunk)(nil),           // 9: deeppool.nodetunnel.v1.TaskStreamChunk
	(*TaskCancel)(nil),                // 10: deeppool.nodetunnel.v1.TaskCancel
	(*ErrorLogEntry)(nil),             // 11: deeppool.nodetunnel.v1.ErrorLogEntry
	(*ErrorLogReport)(nil),            // 12: deeppool.nodetunnel.v1.ErrorLogReport
	(*v1.ChatCompletionRequest)(nil),  // 13: deeppool.llm.v1.ChatCompletionRequest
	(*v1.ChatCompletionResponse)(nil), // 14: deeppool.llm.v1.ChatCompletionResponse
	(*v1.ChatCompletionChunk)(nil),    // 15: deeppool.llm.v1.ChatCompletionChunk
}
var file_node_tunnel_proto_depIdxs = []int32{
	4,  // 0: deeppool.nodetunnel.v1.ClientMessage.register:type_name -> deeppool.nodetunnel.v1.RegisterRequest
	6,  // 1: deeppool.nodetunnel.v1.ClientMessage.heartbeat:type_name -> deeppool.nodetunnel.v1.Heartbeat
	8,  // 2: deeppool.nodetunnel.v1.ClientMessage.task_result:type_name -> deeppool.nodetunnel.v1.TaskResult
	9,  // 3: deeppool.nodetunnel.v1.ClientMessage.task_chunk:type_name -> deeppool.nodetunnel.v1.TaskStreamChunk
	3,  // 4: deeppool.nodetunnel.v1.ClientMessage.update_models:type_name -> deeppool.nodetunnel.v1.UpdateModelsNotify
	12, // 5: deeppool.nodetunnel.v1.ClientMessage.error_log:type_name -> deeppool.nodetunnel.v1.ErrorLogReport
	5,  // 6: deeppool.nodetunnel.v1.ServerMessage.register_ack:type_name -> deeppool.nodetunnel.v1.RegisterResponse
	6,  // 7: deeppool.nodetunnel.v1.ServerMessage.heartbeat:type_name -> deeppool.nodetunnel.v1.Heartbeat
	7,  // 8: deeppool.nodetunnel.v1.ServerMessage.inference_task:type_name -> deeppool.nodetunnel.v1.InferenceTask
	10, // 9: deeppool.nodetunnel.v1.ServerMessage.task_cancel:type_name -> deeppool.nodetunnel.v1.TaskCancel
	2,  // 10: deeppool.nodetunnel.v1.ServerMessage.reload_models:type_name -> deeppool.nodetunnel.v1.ReloadModelsCommand
	13, // 11: deeppool.nodetunnel.v1.InferenceTask.request:type_name -> deeppool.llm.v1.ChatCompletionRequest
	14, // 12: deeppool.nodetunnel.v1.TaskResult.response:type_name -> deeppool.llm.v1.ChatCompletionResponse
	15, // 13: deeppool.nodetunnel.v1.TaskStreamChunk.chunk:type_name -> deeppool.llm.v1.ChatCompletionChunk
	11, // 14: deeppool.nodetunnel.v1.ErrorLogReport.entries:type_name -> deeppool.nodetunnel.v1.ErrorLogEntry
	0,  // 15: deeppool.nodetunnel.v1.NodeTunnelService.Tunnel:input_type -> deeppool.nodetunnel.v1.ClientMessage
	1,  // 16: deeppool.nodetunnel.v1.NodeTunnelService.Tunnel:output_type -> deeppool.nodetunnel.v1.ServerMessage
	16, // [16:17] is the sub-list for method output_type
	15, // [15:16] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_node_tunnel_proto_init() }
func file_node_tunnel_proto_init() {
	if File_node_tunnel_proto != nil {
		return
	}
	file_node_tunnel_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientMessage_Register)(nil),
		(*ClientMessage_Heartbeat)(nil),
		(*ClientMessage_TaskResult)(nil),
		(*ClientMessage_TaskChunk)(nil),
		(*ClientMessage_UpdateModels)(nil),
		(*ClientMessage_ErrorLog)(nil),
	}
	file_node_tunnel_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_RegisterAck)(nil),
		(*ServerMessage_Heartbeat)(nil),
		(*ServerMessage_InferenceTask)(nil),
		(*ServerMessage_TaskCancel)(nil),
		(*ServerMessage_ReloadModels)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_tunnel_proto_rawDesc), len(file_node_tunnel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_node_tunnel_proto_goTypes,
		DependencyIndexes: file_node_tunnel_proto_depIdxs,
		MessageInfos:      file_node_tunnel_proto_msgTypes,
	}.Build()
	File_node_tunnel_proto = out.File
	file_node_tunnel_proto_goTypes = nil
	file_node_tunnel_proto_depIdxs = nil
}
