// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: node_tunnel.proto

package nodetunnelv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeTunnelService_Tunnel_FullMethodName = "/deeppool.nodetunnel.v1.NodeTunnelService/Tunnel"
)

// NodeTunnelServiceClient is the client API for NodeTunnelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ─────────────────────────────────────────────────
// NodeTunnelService — client ↔ nodemanager 控制面双向流隧道
//
// 设计目标：
// 1. 长连接：client 推理服务启动后建立并维持 TCP 级长连接
// 2. 安全鉴权：连接建立时首条消息完成身份验证
// 3. 心跳保活：双向定时心跳，超时自动剔除
// 4. 任务通道：nodemanager 下发推理任务，client 回传结果（支持流式）
// 5. 极致性能：基于 gRPC 双向流，避免频繁连接建立开销
// ─────────────────────────────────────────────────
type NodeTunnelServiceClient interface {
	// Tunnel 双向流：承载注册鉴权、心跳、任务下发与结果回传
	Tunnel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error)
}

type nodeTunnelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeTunnelServiceClient(cc grpc.ClientConnInterface) NodeTunnelServiceClient {
	return &nodeTunnelServiceClient{cc}
}

func (c *nodeTunnelServiceClient) Tunnel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeTunnelService_ServiceDesc.Streams[0], NodeTunnelService_Tunnel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeTunnelService_TunnelClient = grpc.BidiStreamingClient[ClientMessage, ServerMessage]

// NodeTunnelServiceServer is the server API for NodeTunnelService service.
// All implementations must embed UnimplementedNodeTunnelServiceServer
// for forward compatibility.
//
// ─────────────────────────────────────────────────
// NodeTunnelService — client ↔ nodemanager 控制面双向流隧道
//
// 设计目标：
// 1. 长连接：client 推理服务启动后建立并维持 TCP 级长连接
// 2. 安全鉴权：连接建立时首条消息完成身份验证
// 3. 心跳保活：双向定时心跳，超时自动剔除
// 4. 任务通道：nodemanager 下发推理任务，client 回传结果（支持流式）
// 5. 极致性能：基于 gRPC 双向流，避免频繁连接建立开销
// ─────────────────────────────────────────────────
type NodeTunnelServiceServer interface {
	// Tunnel 双向流：承载注册鉴权、心跳、任务下发与结果回传
	Tunnel(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error
	mustEmbedUnimplementedNodeTunnelServiceServer()
}

// UnimplementedNodeTunnelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeTunnelServiceServer struct{}

func (UnimplementedNodeTunnelServiceServer) Tunnel(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error {
	return status.Error(codes.Unimplemented, "method Tunnel not implemented")
}
func (UnimplementedNodeTunnelServiceServer) mustEmbedUnimplementedNodeTunnelServiceServer() {}
func (UnimplementedNodeTunnelServiceServer) testEmbeddedByValue()                           {}

// UnsafeNodeTunnelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeTunnelServiceServer will
// result in compilation errors.
type UnsafeNodeTunnelServiceServer interface {
	mustEmbedUnimplementedNodeTunnelServiceServer()
}

func RegisterNodeTunnelServiceServer(s grpc.ServiceRegistrar, srv NodeTunnelServiceServer) {
	// If the following call panics, it indicates UnimplementedNodeTunnelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeTunnelService_ServiceDesc, srv)
}

func _NodeTunnelService_Tunnel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeTunnelServiceServer).Tunnel(&grpc.GenericServerStream[ClientMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeTunnelService_TunnelServer = grpc.BidiStreamingServer[ClientMessage, ServerMessage]

// NodeTunnelService_ServiceDesc is the grpc.ServiceDesc for NodeTunnelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeTunnelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "deeppool.nodetunnel.v1.NodeTunnelService",
	HandlerType: (*NodeTunnelServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Tunnel",
			Handler:       _NodeTunnelService_Tunnel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "node_tunnel.proto",
}
