"""Device initialization API — register-first architecture.

Core design: device registration and model loading are decoupled.
  Step 1 (init_device): register device → get assigned config → persist credential → start reporter
  Step 2 (background):  download & load model → start tunnel → update device status to ready

Key constraint: tunnel connection must be established AFTER model loading completes.
  If tunnel connects before the engine is ready, nodemanager may dispatch inference
  tasks immediately, causing user-facing failures or long blocking.

Even if model download/loading fails, the device registration info is already collected.

simei is generated by the Python device fingerprint module; no external input needed.
"""

from __future__ import annotations

import json
import logging
import threading

from fastapi import APIRouter

from config import get_config
from rpc.platform_client import get_shared_platform_client
from service.connection_manager import get_connection_manager
from service.credential import DeviceCredential, save_credential
from service.device_fingerprint import get_cached_simei
from service.device_info import get_device_hardware_info
from service.manager import get_service_manager

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/init", tags=["init"])


def _normalize_supported_models(payload: dict) -> list[str]:
    """Extract and normalize the supported-models list from the request payload."""
    supported = payload.get("supported_models")
    if isinstance(supported, list):
        return [str(item).strip().lower() for item in supported if str(item).strip()]
    return []


# ─────────── 设备初始化 API ───────────

@router.post("/device")
def init_device(payload: dict) -> dict:
    """Register-first initialization: register device → get assigned config → async load model.

    Flow:
      1. Generate device fingerprint (simei) and collect hardware info
      2. Register device to platform (triggers AutoAssignModels on server)
      3. Get deploy configs from platform (now based on actual assignment)
      4. Register model configs to local ServiceManager
      5. Persist credential, cleanup old connections, start log reporter
      6. Async download + load first model in background thread
      7. After model ready: start tunnel + update device status to ready
    """
    token = str(payload.get("token", "")).strip()

    if not token:
        logger.warning("init_device called without token")
        return {"code": 400, "message": "token is required"}

    try:
        simei = get_cached_simei()
    except RuntimeError as exc:
        logger.error("failed to generate device fingerprint: %s", exc)
        return {"code": 500, "message": f"fingerprint generation failed: {exc}"}

    supported_models = _normalize_supported_models(payload)
    logger.info("init_device start simei=%s supported_models=%s", simei, supported_models)

    try:
        client = get_shared_platform_client(token)
        cm = get_connection_manager()

        # ── Step 1: Collect hardware and register device to platform ──
        # Triggers AutoAssignModels on the server side.
        hw = get_device_hardware_info()
        device_config = {
            "init_stage": "registering",
            "simei": simei,
            "hardware": hw.to_dict(),
        }

        try:
            client.register_device(
                simei=simei,
                device_ip="127.0.0.1",
                device_config=json.dumps(device_config, ensure_ascii=False),
                registered_models=[],  # no model loaded yet
            )
            logger.info("device registered to platform simei=%s", simei)
        except RuntimeError as register_err:
            err_msg = str(register_err).lower()
            if "duplicate resource" in err_msg or "already exists" in err_msg:
                logger.info("device already registered, will fetch current assignment simei=%s", simei)
            else:
                raise

        # ── Step 2: Get deploy configs based on actual server-side assignment ──
        deploy_configs = client.get_multi_model_deploy_configs(
            simei=simei, supported_models=supported_models,
        )
        if not deploy_configs:
            logger.warning("init_device: platform returned no model configs after registration")
            return {"code": 500, "message": "no model deploy config available"}

        # ── Step 3: Register model configs to local ServiceManager ──
        manager = get_service_manager()
        manager.register_models(deploy_configs)

        # ── Step 4: Persist credential + cleanup old connections + start reporter ──
        save_credential(DeviceCredential(simei=simei, token=token))
        cm.shutdown_all()  # cleanup any pre-existing tunnel / reporter
        cm.start_reporter(simei, token)

        # ── Step 5: Async load model + start tunnel when ready ──
        _start_async_model_loading(
            simei=simei,
            token=token,
            deploy_configs=deploy_configs,
            manager=manager,
        )

        logger.info(
            "init_device completed simei=%s deploy_configs=%d, model loading in background",
            simei, len(deploy_configs),
        )
        return {
            "code": 0,
            "message": "ok",
            "data": {
                "device_ip": "127.0.0.1",
                "device_config": device_config,
                "model_loading": True,
            },
        }
    except Exception as exc:
        logger.exception("init_device failed simei=%s err=%s", simei, exc)
        return {
            "code": 500,
            "message": f"init failed: {exc}",
        }


# ─────────── 异步模型加载 ───────────

def _start_async_model_loading(
    simei: str,
    token: str,
    deploy_configs: list,
    manager,
) -> None:
    """Download and load the first model in a background thread.

    After loading completes:
      1. Start nodemanager tunnel (engine is ready, safe to accept inference tasks)
      2. Update platform device config to init_stage="ready"
    Failure only logs a warning — device registration is not affected.
    """
    def _load_worker():
        first_cfg = deploy_configs[0]
        logger.info("async model loading started: %s", first_cfg.model_name)

        try:
            running = manager.ensure_service(first_cfg)
            logger.info(
                "async model loaded: %s engine=%s rpc=%s:%d",
                running.model_name, running.engine_type,
                running.rpc_host, running.rpc_port,
            )

            # Start tunnel only after model is ready
            cm = get_connection_manager()
            cm.start_tunnel(simei, token, running, manager)

            # Update platform device status to ready
            _update_device_status_to_ready(
                simei=simei,
                token=token,
                running=running,
                manager=manager,
                deploy_configs=deploy_configs,
            )
        except Exception as exc:
            logger.error(
                "async model loading failed: %s error=%s", first_cfg.model_name, exc,
                exc_info=True,
            )

    thread = threading.Thread(
        target=_load_worker,
        name="async-model-loader",
        daemon=True,
    )
    thread.start()


def _update_device_status_to_ready(
    simei: str,
    token: str,
    running,
    manager,
    deploy_configs: list,
) -> None:
    """Update platform device config to ready after model loading completes.

    Reports actually loaded models via registered_models field.
    Uses the shared PlatformClient (no per-call channel creation).
    """
    try:
        client = get_shared_platform_client(token)
        hw = get_device_hardware_info()
        device_config = {
            "init_stage": "ready",
            "simei": simei,
            "llm_rpc_host": running.rpc_host,
            "llm_rpc_port": running.rpc_port,
            "llm_engine": running.engine_type,
            "hardware": hw.to_dict(),
        }
        if manager.engine_config is not None:
            device_config["engine_config"] = manager.engine_config.to_dict()

        loaded_models = [running.model_name]

        try:
            client.update_device(
                simei=simei,
                device_config=json.dumps(device_config, ensure_ascii=False),
                registered_models=loaded_models,
            )
            logger.info("device status updated to ready simei=%s registered_models=%s", simei, loaded_models)
        except Exception as update_err:
            logger.warning("UpdateDevice failed (%s), trying re-register", update_err)
            try:
                client.register_device(
                    simei=simei,
                    device_ip="127.0.0.1",
                    device_config=json.dumps(device_config, ensure_ascii=False),
                    registered_models=loaded_models,
                )
            except RuntimeError:
                logger.warning("re-register also failed, device status may stay as 'registering'")

    except Exception as exc:
        logger.warning("failed to update device status to ready: %s", exc)


# --- Stop service / Status query ---

@router.post("/stop")
def stop_service() -> dict:
    """Stop inference service and disconnect nodemanager tunnel.

    Called by the frontend "pause service" button. After stopping, the user
    must re-initialize to resume. Online status is managed by NodeManager's
    real-time connection — no explicit status report needed.
    """
    cm = get_connection_manager()
    cm.shutdown_all()

    manager = get_service_manager()
    manager.shutdown()
    logger.info("stop_service: inference service stopped")

    return {"code": 0, "message": "ok"}


@router.get("/status")
def init_status() -> dict:
    """Query local inference service status (supports multi-model).

    Returns all registered models' status. Frontend uses:
      - infer_ready=True  → at least one model loaded, ready to infer
      - infer_ready=False → model still loading or init_device not called
      - models: status list of all registered models
    """
    manager = get_service_manager()
    running = manager.get_running_service()
    models = manager.list_models()

    if running is None:
        return {
            "code": 0,
            "message": "ok",
            "data": {
                "infer_ready": False,
                "models": models,
            },
        }

    return {
        "code": 0,
        "message": "ok",
        "data": {
            "infer_ready": True,
            "model_name": running.model_name,
            "engine_type": running.engine_type,
            "rpc_host": running.rpc_host,
            "rpc_port": running.rpc_port,
            "models": models,
        },
    }


