"""Device initialization API — register-first architecture.

Core design: device registration and model loading are decoupled.
  Step 1 (init_device): register device → get assigned config → persist credential → start reporter
  Step 2 (background):  download & load model → start tunnel → update device status to ready

Key constraint: tunnel connection must be established AFTER model loading completes.
  If tunnel connects before the engine is ready, nodemanager may dispatch inference
  tasks immediately, causing user-facing failures or long blocking.

Even if model download/loading fails, the device registration info is already collected.

simei is generated by the Python device fingerprint module; no external input needed.
"""

from __future__ import annotations

import json
import logging
import threading

from fastapi import APIRouter

from config import get_config
from rpc.platform_client import get_shared_platform_client
from service.connection_manager import get_connection_manager
from service.credential import DeviceCredential, save_credential
from service.device_fingerprint import get_cached_simei
from service.device_info import get_device_hardware_info
from service.manager import get_service_manager

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/init", tags=["init"])

# ─── Device status tracking (shared with stats API for frontend polling) ───
# Updated during init_device and auto-restore flows.
_device_status: str = "active"  # "active" / "blocked" / "cheating"


def get_device_status() -> str:
    """Return current device status for frontend display."""
    return _device_status


def set_device_status(status: str) -> None:
    """Update cached device status (called after registration/query)."""
    global _device_status
    _device_status = status


# Map device status to user-facing block reason messages.
_BLOCK_REASONS = {
    "blocked": (
        "This device has been blocked by the platform security policy. "
        "Possible causes: (1) this installation package lacks security hardening — "
        "please download the latest version; (2) application files have been tampered with — "
        "please re-download a fresh installation package."
    ),
    "cheating": (
        "This device has been flagged for suspicious activity and is banned from the platform."
    ),
}


def _blocked_reason(status: str) -> str:
    """Return a user-facing explanation for a non-active device status."""
    return _BLOCK_REASONS.get(status, f"Device status is '{status}', not allowed to serve inference.")


def _normalize_supported_models(payload: dict) -> list[str]:
    """Extract and normalize the supported-models list from the request payload."""
    supported = payload.get("supported_models")
    if isinstance(supported, list):
        return [str(item).strip().lower() for item in supported if str(item).strip()]
    return []


def _collect_security_status() -> dict:
    """Collect runtime security status for platform reporting.

    Gathers integrity verification result and device binding status from
    environment variables set by the runtime hook and binding module.
    """
    import os
    status: dict = {}

    # Integrity verification (set by runtime hook via env var)
    integrity_failed = os.environ.get("_DEEPNODE_INTEGRITY_FAILED")
    if integrity_failed:
        status["integrity_passed"] = False
        status["integrity_detail"] = os.environ.get("_DEEPNODE_INTEGRITY_DETAIL", "")
    else:
        status["integrity_passed"] = True

    # Device binding status
    try:
        from service.device_binding import get_hardware_binding_factors
        factors = get_hardware_binding_factors()
        status["device_bound"] = len(factors) > 0
        status["binding_factors"] = len(factors)
    except Exception:
        status["device_bound"] = False

    return status


# ─────────── 设备初始化 API ───────────

@router.post("/device")
def init_device(payload: dict) -> dict:
    """Register-first initialization: register device → get assigned config → async load model.

    Flow:
      1. Generate device fingerprint (simei) and collect hardware info
      2. Register device to platform (triggers AutoAssignModels on server)
      3. Get deploy configs from platform (now based on actual assignment)
      4. Register model configs to local ServiceManager
      5. Persist credential, cleanup old connections, start log reporter
      6. Async download + load first model in background thread
      7. After model ready: start tunnel + update device status to ready
    """
    token = str(payload.get("token", "")).strip()

    if not token:
        logger.warning("init_device called without token")
        return {"code": 400, "message": "token is required"}

    try:
        simei = get_cached_simei()
    except RuntimeError as exc:
        logger.error("failed to generate device fingerprint: %s", exc)
        return {"code": 500, "message": f"fingerprint generation failed: {exc}"}

    supported_models = _normalize_supported_models(payload)
    logger.info("init_device start simei=%s supported_models=%s", simei, supported_models)

    try:
        client = get_shared_platform_client(token)
        cm = get_connection_manager()

        # ── Step 1: Collect hardware and register device to platform ──
        # Triggers AutoAssignModels on the server side.
        hw = get_device_hardware_info()
        from version import get_version as _get_version
        device_config = {
            "init_stage": "registering",
            "simei": simei,
            "deepnode_version": _get_version(),
            "hardware": hw.to_dict(),
        }

        try:
            device_info = client.register_device(
                simei=simei,
                device_ip="127.0.0.1",
                device_config=json.dumps(device_config, ensure_ascii=False),
                registered_models=[],  # no model loaded yet
            )
            logger.info("device registered to platform simei=%s status=%s", simei, device_info.status)
            set_device_status(device_info.status)

            # Check if the device was blocked by platform security policy.
            # This happens when the build lacks security hardening or integrity check fails.
            if device_info.status != "active":
                reason = _blocked_reason(device_info.status)
                logger.warning(
                    "device blocked by platform security policy: simei=%s status=%s reason=%s",
                    simei, device_info.status, reason,
                )
                return {
                    "code": 403,
                    "message": reason,
                    "data": {"status": device_info.status, "simei": simei},
                }
        except RuntimeError as register_err:
            err_msg = str(register_err).lower()
            if "duplicate resource" in err_msg or "already exists" in err_msg:
                logger.info("device already registered, checking current status simei=%s", simei)
                existing = client.get_device(simei)
                if existing and existing.status != "active":
                    # Device is blocked — attempt re-evaluation by submitting the
                    # latest device_config (with security status) via UpdateDevice.
                    # Platform's evaluateDeviceSecurity will auto-restore to "active"
                    # if the new build passes integrity checks.
                    restored = _try_reactivate_blocked_device(
                        client=client, simei=simei, hw=hw,
                    )
                    if restored and restored.status == "active":
                        logger.info(
                            "blocked device reactivated after security re-evaluation simei=%s",
                            simei,
                        )
                        set_device_status("active")
                    else:
                        final_status = restored.status if restored else existing.status
                        set_device_status(final_status)
                        reason = _blocked_reason(final_status)
                        logger.warning(
                            "existing device is blocked: simei=%s status=%s reason=%s",
                            simei, final_status, reason,
                        )
                        return {
                            "code": 403,
                            "message": reason,
                            "data": {"status": final_status, "simei": simei},
                        }
            else:
                raise

        # ── Step 2: Get deploy configs based on actual server-side assignment ──
        deploy_configs = client.get_multi_model_deploy_configs(
            simei=simei, supported_models=supported_models,
        )
        if not deploy_configs:
            logger.warning("init_device: platform returned no model configs after registration")
            return {"code": 500, "message": "no model deploy config available"}

        # ── Step 3: Register model configs to local ServiceManager ──
        manager = get_service_manager()
        manager.register_models(deploy_configs)

        # ── Step 4: Persist credential + cleanup old connections + start reporter ──
        save_credential(DeviceCredential(simei=simei, token=token))
        cm.shutdown_all()  # cleanup any pre-existing tunnel / reporter
        cm.start_reporter(simei, token)

        # ── Step 5: Async load model + start tunnel when ready ──
        _start_async_model_loading(
            simei=simei,
            token=token,
            deploy_configs=deploy_configs,
            manager=manager,
        )

        logger.info(
            "init_device completed simei=%s deploy_configs=%d, model loading in background",
            simei, len(deploy_configs),
        )
        return {
            "code": 0,
            "message": "ok",
            "data": {
                "device_ip": "127.0.0.1",
                "device_config": device_config,
                "model_loading": True,
            },
        }
    except Exception as exc:
        logger.exception("init_device failed simei=%s err=%s", simei, exc)
        return {
            "code": 500,
            "message": f"init failed: {exc}",
        }


# ─────────── Blocked device reactivation ───────────

def _try_reactivate_blocked_device(client, simei: str, hw) -> object | None:
    """Submit latest device_config with security status to trigger platform re-evaluation.

    When a blocked device downloads a new (properly hardened) build, the integrity
    check will pass. By calling UpdateDevice with the new security status, the
    platform's evaluateDeviceSecurity will detect integrity_passed=True and restore
    the device status to active.

    Returns the updated device info, or None on failure.
    """
    try:
        security = _collect_security_status()
        from version import get_version as _get_version
        device_config = {
            "init_stage": "reactivating",
            "simei": simei,
            "deepnode_version": _get_version(),
            "hardware": hw.to_dict(),
            "security": security,
        }
        updated = client.update_device(
            simei=simei,
            device_config=json.dumps(device_config, ensure_ascii=False),
        )
        logger.info(
            "reactivation attempt: simei=%s updated_status=%s integrity_passed=%s",
            simei, updated.status if updated else "unknown",
            security.get("integrity_passed"),
        )
        return updated
    except Exception as exc:
        logger.warning("reactivation UpdateDevice failed: simei=%s err=%s", simei, exc)
        return None


# ─────────── 异步模型加载 ───────────

def _start_async_model_loading(
    simei: str,
    token: str,
    deploy_configs: list,
    manager,
) -> None:
    """Download and load the first model in a background thread.

    After loading completes:
      1. Start nodemanager tunnel (engine is ready, safe to accept inference tasks)
      2. Update platform device config to init_stage="ready"
    Failure only logs a warning — device registration is not affected.
    """
    def _load_worker():
        first_cfg = deploy_configs[0]
        logger.info("async model loading started: %s", first_cfg.model_name)

        try:
            running = manager.ensure_service(first_cfg)
            logger.info(
                "async model loaded: %s engine=%s rpc=%s:%d",
                running.model_name, running.engine_type,
                running.rpc_host, running.rpc_port,
            )

            # Start tunnel only after model is ready
            cm = get_connection_manager()
            cm.start_tunnel(simei, token, running, manager)

            # Update platform device status to ready
            _update_device_status_to_ready(
                simei=simei,
                token=token,
                running=running,
                manager=manager,
                deploy_configs=deploy_configs,
            )
        except Exception as exc:
            logger.error(
                "async model loading failed: %s error=%s", first_cfg.model_name, exc,
                exc_info=True,
            )

    thread = threading.Thread(
        target=_load_worker,
        name="async-model-loader",
        daemon=True,
    )
    thread.start()


def _update_device_status_to_ready(
    simei: str,
    token: str,
    running,
    manager,
    deploy_configs: list,
) -> None:
    """Update platform device config to ready after model loading completes.

    Reports actually loaded models via registered_models field.
    Uses the shared PlatformClient (no per-call channel creation).
    """
    try:
        client = get_shared_platform_client(token)
        hw = get_device_hardware_info()
        from version import get_version as _get_version
        device_config = {
            "init_stage": "ready",
            "simei": simei,
            "deepnode_version": _get_version(),
            "llm_rpc_host": running.rpc_host,
            "llm_rpc_port": running.rpc_port,
            "llm_engine": running.engine_type,
            "hardware": hw.to_dict(),
        }
        if manager.engine_config is not None:
            device_config["engine_config"] = manager.engine_config.to_dict()

        # Report integrity verification status to platform
        device_config["security"] = _collect_security_status()

        loaded_models = [running.model_name]

        try:
            client.update_device(
                simei=simei,
                device_config=json.dumps(device_config, ensure_ascii=False),
                registered_models=loaded_models,
            )
            logger.info("device status updated to ready simei=%s registered_models=%s", simei, loaded_models)
        except Exception as update_err:
            logger.warning("UpdateDevice failed (%s), trying re-register", update_err)
            try:
                client.register_device(
                    simei=simei,
                    device_ip="127.0.0.1",
                    device_config=json.dumps(device_config, ensure_ascii=False),
                    registered_models=loaded_models,
                )
            except RuntimeError:
                logger.warning("re-register also failed, device status may stay as 'registering'")

    except Exception as exc:
        logger.warning("failed to update device status to ready: %s", exc)


# --- Stop service / Status query ---

@router.post("/stop")
def stop_service() -> dict:
    """Stop inference service and disconnect nodemanager tunnel.

    Called by the frontend "pause service" button. After stopping, the user
    must re-initialize to resume. Online status is managed by NodeManager's
    real-time connection — no explicit status report needed.
    """
    cm = get_connection_manager()
    cm.shutdown_all()

    manager = get_service_manager()
    manager.shutdown()
    logger.info("stop_service: inference service stopped")

    return {"code": 0, "message": "ok"}


@router.get("/status")
def init_status() -> dict:
    """Query local inference service status (supports multi-model).

    Returns all registered models' status. Frontend uses:
      - infer_ready=True  → at least one model loaded, ready to infer
      - infer_ready=False → model still loading or init_device not called
      - models: status list of all registered models
    """
    manager = get_service_manager()
    running = manager.get_running_service()
    models = manager.list_models()

    if running is None:
        return {
            "code": 0,
            "message": "ok",
            "data": {
                "infer_ready": False,
                "models": models,
            },
        }

    return {
        "code": 0,
        "message": "ok",
        "data": {
            "infer_ready": True,
            "model_name": running.model_name,
            "engine_type": running.engine_type,
            "rpc_host": running.rpc_host,
            "rpc_port": running.rpc_port,
            "models": models,
        },
    }


