"""DeepNode local server entry point — provides device initialization and inference APIs.

Two run modes:
  - Tauri sidecar mode: launched by Tauri desktop app, simei generated by Python
  - Standalone mode: launched via CLI, auto-generates simei + auto-initializes

On startup, attempts to restore inference service from persisted device credential:
  read credential → request model deploy config from platform → start gRPC inference
  server. When the inference engine is ready, connects to nodemanager via
  bidirectional gRPC stream to receive remote inference tasks.
  If no credential or no available model, waits for frontend-triggered init_device.
"""

import argparse
import logging
import multiprocessing
import sys
import threading

# PyInstaller frozen binaries require freeze_support() before any other code.
# Without this, multiprocessing spawn on macOS re-executes the entire script,
# causing a duplicate process to start after Ctrl+C kills the original.
if getattr(sys, 'frozen', False):
    multiprocessing.freeze_support()

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from config import init_config
from log_setup import setup_logging
from api import init_router, stats_router, dashboard_router, auth_router


def _parse_cli_args() -> argparse.Namespace:
    """Parse CLI arguments, supporting standalone run mode."""
    parser = argparse.ArgumentParser(
        description="DeepNode Local Worker — inference node local service",
    )
    parser.add_argument(
        "--config", "-c",
        type=str,
        default=None,
        help="Config file path (default: localserver/config.yaml)",
    )
    parser.add_argument(
        "--standalone",
        action="store_true",
        default=False,
        help="Enable standalone mode (auto-generate simei + auto-init)",
    )
    parser.add_argument(
        "--token", "-t",
        type=str,
        default=None,
        help="Platform auth token (overrides standalone.token in config)",
    )
    parser.add_argument(
        "--account", "-a",
        type=str,
        default=None,
        help="Platform login account (overrides standalone.account in config)",
    )
    parser.add_argument(
        "--password", "-p",
        type=str,
        default=None,
        help="Platform login password (overrides standalone.password in config)",
    )
    # Use parse_known_args to ignore unknown args injected by PyInstaller bootloader (-B -S -I)
    args, _ = parser.parse_known_args()
    return args


# Parse CLI arguments
_cli_args = _parse_cli_args()

# Load config (CLI --config takes priority)
cfg = init_config(path=_cli_args.config)

# CLI arguments override config file values
if _cli_args.standalone:
    cfg.standalone.enabled = True
if _cli_args.token:
    cfg.standalone.token = _cli_args.token
if _cli_args.account:
    cfg.standalone.account = _cli_args.account
if _cli_args.password:
    cfg.standalone.password = _cli_args.password

# Initialize logging
setup_logging(
    level=cfg.log.level,
    log_dir=cfg.log.log_dir,
    file_name=cfg.log.file_name,
    backup_count=cfg.log.backup_count,
)
logger = logging.getLogger(__name__)

app = FastAPI(title="DeepNode Local Worker")

# Restrict CORS to localhost origins only (frontend runs on different local port)
_LOCAL_ORIGINS = [
    "http://localhost",
    "http://127.0.0.1",
    "https://localhost",
    "https://127.0.0.1",
    "tauri://localhost",
    "https://tauri.localhost",
]
# Expand with common dev ports
_ALLOWED_ORIGINS = []
for origin in _LOCAL_ORIGINS:
    _ALLOWED_ORIGINS.append(origin)
    for port in (1420, 3000, 5173, 8080, 8765):
        _ALLOWED_ORIGINS.append(f"{origin}:{port}")

app.add_middleware(
    CORSMiddleware,
    allow_origins=_ALLOWED_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(init_router)
app.include_router(stats_router)
app.include_router(dashboard_router)
app.include_router(auth_router)

# If Vue SPA build artifacts are detected, mount static file middleware
from api.dashboard import get_web_dist_dir

_web_dist = get_web_dist_dir()
if _web_dist is not None:
    from fastapi.staticfiles import StaticFiles
    assets_dir = _web_dist / 'assets'
    if assets_dir.is_dir():
        app.mount('/assets', StaticFiles(directory=str(assets_dir)), name='vue-assets')
        logger.info("mounted Vue SPA assets from %s", assets_dir)
    app.mount('/static', StaticFiles(directory=str(_web_dist)), name='vue-static')
    logger.info("Vue SPA web UI enabled at http://127.0.0.1:%d/", cfg.server.port)


@app.get("/health")
def health() -> dict:
    """健康检查"""
    return {"status": "ok", "service": "deepnode-local-worker"}


# ─────────────────────────────────────────────────
# 启动时自动尝试恢复推理服务并建立 nodemanager 长连接
# ─────────────────────────────────────────────────

def _try_restore_and_connect() -> None:
    """Restore inference service from persisted credential.

    Strategy:
      1. Read credential → get deploy configs → register models → start reporter
      2. Load first model (sync, runs in daemon thread)
      3. Report loaded models via UpdateDevice → then start tunnel

    Tunnel must be established after model loading completes to prevent nodemanager
    from dispatching tasks to an unprepared engine.

    Any failure only logs a warning; HTTP service startup is not blocked.
    """
    from service.credential import load_credential
    from rpc.platform_client import get_shared_platform_client
    from service.connection_manager import get_connection_manager
    from service.manager import get_service_manager
    from service.token_manager import init_token_manager

    cred = load_credential()
    if cred is None:
        logger.info("no device credential found, skip auto-restore (waiting for init_device)")
        return

    logger.info("auto-restore: found credential simei=%s, requesting deploy configs from platform", cred.simei)

    # Initialize TokenManager in sidecar mode (token only, no auto-refresh)
    init_token_manager(token=cred.token)

    cm = get_connection_manager()
    try:
        client = get_shared_platform_client(cred.token)

        # Check if device is blocked before proceeding with model loading.
        # If blocked, submit fresh security status to trigger platform re-evaluation.
        try:
            existing = client.get_device(cred.simei)
            if existing and existing.status != "active":
                logger.warning(
                    "auto-restore: device is %s, attempting reactivation simei=%s",
                    existing.status, cred.simei,
                )
                from service.device_info import get_device_hardware_info as _get_hw
                from api.init import _try_reactivate_blocked_device, set_device_status
                hw = _get_hw()
                restored = _try_reactivate_blocked_device(
                    client=client, simei=cred.simei, hw=hw,
                )
                if not restored or restored.status != "active":
                    final_status = restored.status if restored else existing.status
                    set_device_status(final_status)
                    logger.warning(
                        "auto-restore: device still blocked after reactivation attempt simei=%s status=%s",
                        cred.simei, final_status,
                    )
                    return
                logger.info("auto-restore: device reactivated simei=%s", cred.simei)
                set_device_status("active")
        except Exception as check_exc:
            logger.warning("auto-restore: device status check failed: %s", check_exc)

        # Get deploy configs from platform (device already registered)
        deploy_configs = client.get_multi_model_deploy_configs(
            simei=cred.simei,
            supported_models=[],
        )
        if not deploy_configs:
            logger.warning("auto-restore: platform returned no model configs, skip")
            return

        # Step 1: register model configs + start log reporter
        manager = get_service_manager()
        manager.register_models(deploy_configs)
        cm.start_reporter(cred.simei, cred.token)

        logger.info("auto-restore: log reporter started, registered=%d models", len(deploy_configs))

        # Step 2: load first model (sync blocking in daemon thread)
        first_cfg = deploy_configs[0]
        try:
            running = manager.ensure_service(first_cfg)
            logger.info(
                "auto-restore: model loaded model=%s engine=%s rpc=%s:%d",
                running.model_name, running.engine_type,
                running.rpc_host, running.rpc_port,
            )
        except Exception as model_exc:
            logger.warning("auto-restore: model loading failed (device still registered): %s", model_exc)
            return

        # Step 3: report actually loaded model to platform
        try:
            import json
            from service.device_info import get_device_hardware_info
            from api.init import _collect_security_status
            from version import get_version as _get_version
            hw = get_device_hardware_info()
            device_config = {
                "init_stage": "ready",
                "simei": cred.simei,
                "deepnode_version": _get_version(),
                "llm_rpc_host": running.rpc_host,
                "llm_rpc_port": running.rpc_port,
                "llm_engine": running.engine_type,
                "hardware": hw.to_dict(),
                "security": _collect_security_status(),
            }
            if manager.engine_config is not None:
                device_config["engine_config"] = manager.engine_config.to_dict()
            client.update_device(
                simei=cred.simei,
                device_config=json.dumps(device_config, ensure_ascii=False),
                registered_models=[running.model_name],
            )
            logger.info("auto-restore: reported registered_models=[%s]", running.model_name)
        except Exception as report_exc:
            logger.warning("auto-restore: failed to report registered_models: %s", report_exc)

        # Step 4: start tunnel after model is ready
        cm.start_tunnel(cred.simei, cred.token, running, manager)
        logger.info("auto-restore: tunnel connected (model ready) simei=%s", cred.simei)

    except Exception as exc:
        logger.warning("auto-restore: failed: %s", exc)


def _resolve_standalone_token() -> str | None:
    """Resolve auth token for standalone mode.

    Priority: direct token > auto-login via account/password.
    Initializes the global TokenManager so that token refresh is possible
    during the process lifetime (password kept in memory only).

    Returns None if token cannot be obtained.
    """
    from service.token_manager import init_token_manager

    # Use directly provided token
    token = cfg.standalone.token.strip()
    account = cfg.standalone.account.strip()
    password = cfg.standalone.password.strip()

    if token:
        logger.info("standalone: using pre-configured token")
        # Initialize TokenManager — if account/password are also provided,
        # auto-refresh will be available; otherwise token-only (no refresh).
        init_token_manager(token=token, account=account, password=password)
        return token

    # Attempt auto-login via account/password
    if not account or not password:
        logger.error(
            "standalone mode requires either --token or --account/--password. "
            "Example: ./deepnode-server --standalone --account myuser --password mypass"
        )
        return None

    logger.info("standalone: logging in with account=%s ...", account)
    try:
        from service.platform_auth import platform_login
        result = platform_login(account=account, password=password)
        cfg.standalone.token = result.token
        logger.info("standalone: login success, user=%s (id=%d)", result.username, result.user_id)

        # Initialize TokenManager with credentials for in-process refresh
        init_token_manager(token=result.token, account=account, password=password)

        return result.token
    except RuntimeError as exc:
        logger.error("standalone: login failed: %s", exc)
        return None


def _standalone_auto_init() -> None:
    """Standalone mode: auto-authenticate → auto-generate simei → auto-init device.

    Equivalent to the user completing "login + join network" in the frontend,
    but fully autonomous on the localserver side.
    """
    from api.init import init_device

    token = _resolve_standalone_token()
    if not token:
        return

    # 调用 init_device API 内部逻辑完成初始化（simei 由其内部自动生成）
    logger.info("standalone: auto-initializing device...")
    result = init_device({"token": token, "supported_models": []})
    logger.info("standalone: init_device result: %s", result)


# ─────────────────────────────────────────────────
# Periodic integrity re-verification (frozen builds only)
# ─────────────────────────────────────────────────

_INTEGRITY_CHECK_INTERVAL_SEC = 300  # 5 minutes

# ─────────────────────────────────────────────────
# Platform health watchdog — detect backend outage and auto-recover
# ─────────────────────────────────────────────────

_WATCHDOG_INTERVAL_SEC = 30          # health probe every 30s
_WATCHDOG_RECOVER_DELAY_SEC = 5      # wait before re-init after recovery
_platform_connected: bool = True     # shared flag for stats API / frontend


def is_platform_connected() -> bool:
    """Return current platform connectivity status (consumed by stats API)."""
    return _platform_connected


def _start_platform_watchdog() -> None:
    """Launch a daemon thread that periodically probes platform manager.

    When the backend becomes unreachable the flag flips to False so the
    frontend can show a disconnected banner.  Once connectivity resumes
    the watchdog automatically re-runs the full init flow (re-register
    device + re-fetch model configs + restart tunnel) to bring the node
    back online without manual intervention.

    Token-expired errors are handled transparently by PlatformClient's
    built-in token refresh mechanism (via TokenManager).  The watchdog
    only marks the platform as disconnected for genuine connectivity
    failures (UNAVAILABLE, DEADLINE_EXCEEDED, etc.).
    """
    import time as _time

    def _watchdog():
        global _platform_connected

        from service.credential import load_credential
        from rpc.platform_client import get_shared_platform_client
        from service.token_manager import get_token_manager

        logger.info("platform watchdog started (interval=%ds)", _WATCHDOG_INTERVAL_SEC)

        consecutive_failures = 0

        while True:
            _time.sleep(_WATCHDOG_INTERVAL_SEC)

            cred = load_credential()
            if cred is None:
                continue

            # Use the latest token from TokenManager (may have been refreshed)
            tm = get_token_manager()
            current_token = tm.token if tm else cred.token

            try:
                client = get_shared_platform_client(current_token)
                client.get_device(cred.simei)

                if not _platform_connected:
                    logger.info("platform watchdog: backend recovered, triggering auto-recovery")
                    _platform_connected = True
                    consecutive_failures = 0

                    _time.sleep(_WATCHDOG_RECOVER_DELAY_SEC)
                    _auto_recover(cred)
                else:
                    if consecutive_failures > 0:
                        logger.info("platform watchdog: connectivity restored after %d failures", consecutive_failures)
                    consecutive_failures = 0

            except Exception as exc:
                consecutive_failures += 1
                was_connected = _platform_connected
                _platform_connected = False

                if was_connected:
                    logger.warning("platform watchdog: backend unreachable — %s", exc)
                elif consecutive_failures % 10 == 0:
                    logger.warning(
                        "platform watchdog: still unreachable (failures=%d) — %s",
                        consecutive_failures, exc,
                    )

    thread = threading.Thread(target=_watchdog, name="platform-watchdog", daemon=True)
    thread.start()


def _auto_recover(cred) -> None:
    """Re-run init flow after backend recovery.

    Reuses the persisted credential to re-register device, fetch model
    configs, and restart the tunnel — same as _try_restore_and_connect
    but invoked mid-flight after detecting recovery.
    """
    try:
        if cfg.standalone.enabled:
            token = cred.token or _resolve_standalone_token()
            if token:
                from api.init import init_device
                result = init_device({"token": token, "supported_models": []})
                logger.info("platform watchdog: auto-recovery init_device result=%s", result)
        else:
            _try_restore_and_connect()
    except Exception as exc:
        logger.warning("platform watchdog: auto-recovery failed: %s", exc)


def _start_periodic_integrity_check() -> None:
    """Launch a daemon thread that periodically re-verifies file integrity.

    Detects runtime file tampering (e.g. attacker replaces files after the
    process starts). On failure, logs a critical error and terminates the
    process to prevent serving with compromised code.
    """
    import os

    def _checker():
        import time as _time
        from service.integrity import verify_integrity

        logger.info("periodic integrity checker started (interval=%ds)",
                     _INTEGRITY_CHECK_INTERVAL_SEC)
        while True:
            _time.sleep(_INTEGRITY_CHECK_INTERVAL_SEC)
            try:
                result = verify_integrity()
                if result is None:
                    continue
                if result.passed:
                    logger.debug("periodic integrity check passed (%d/%d files, %dms)",
                                 result.verified_files, result.total_files,
                                 result.duration_ms)
                else:
                    detail = []
                    if result.mismatched_files:
                        detail.append(f"mismatched={result.mismatched_files[:5]}")
                    if result.missing_files:
                        detail.append(f"missing={result.missing_files[:5]}")
                    logger.critical(
                        "PERIODIC INTEGRITY CHECK FAILED: %s — shutting down",
                        ", ".join(detail),
                    )
                    os.environ['_DEEPNODE_INTEGRITY_FAILED'] = '1'
                    # Force exit — tampered binary must not continue serving
                    os._exit(78)
            except Exception as exc:
                logger.warning("periodic integrity check error: %s", exc)

    thread = threading.Thread(target=_checker, name="integrity-checker", daemon=True)
    thread.start()


@app.on_event("startup")
def on_startup():
    """FastAPI startup: choose startup strategy based on run mode.

    - standalone mode: auto-generate simei + auto-init device
    - sidecar/normal mode: try restoring inference service from persisted credential
    """
    if cfg.standalone.enabled:
        logger.info("standalone mode enabled, starting auto-init...")
        thread = threading.Thread(
            target=_standalone_auto_init,
            name="standalone-auto-init",
            daemon=True,
        )
    else:
        thread = threading.Thread(
            target=_try_restore_and_connect,
            name="infer-auto-restore",
            daemon=True,
        )
    thread.start()
    logger.info("startup thread started (standalone=%s)", cfg.standalone.enabled)

    # Start platform health watchdog for auto-recovery after backend outage
    _start_platform_watchdog()

    # Start periodic integrity re-verification in frozen (standalone) builds
    if getattr(sys, 'frozen', False):
        _start_periodic_integrity_check()


@app.on_event("shutdown")
def on_shutdown():
    """FastAPI shutdown: disconnect all connections, stop engine, release resources."""
    from service.connection_manager import get_connection_manager
    from rpc.platform_client import close_shared_platform_client

    # Shut down tunnel + log reporter
    get_connection_manager().shutdown_all()

    # Close the shared gRPC channel
    close_shared_platform_client()

    # Shut down inference engine and gRPC server, release GPU resources
    from service.manager import get_service_manager
    get_service_manager().shutdown()

    # Close statistics database
    from service.statistics import get_statistics_db
    get_statistics_db().close()

    logger.info("inference service shutdown complete")


if __name__ == "__main__":
    import uvicorn
    from version import get_version

    logger.info(
        "Starting local server v%s on %s:%d (standalone=%s, manager_grpc=%s, nodemanager_grpc=%s)",
        get_version(),
        cfg.server.host,
        cfg.server.port,
        cfg.standalone.enabled,
        cfg.platform.manager_grpc_target,
        cfg.platform.nodemanager_grpc_target,
    )
    uvicorn.run(app, host=cfg.server.host, port=cfg.server.port)
