// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: llm_infer.proto

package llmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_llm_infer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_infer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_llm_infer_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	ModelName     string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_llm_infer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_infer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_llm_infer_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *HealthResponse) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 对齐 OpenAI ChatCompletionRequest
type ChatCompletionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 模型标识（由调度层填充，引擎层可忽略）
	Model string `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	// 消息列表（system / user / assistant / tool）
	Messages []*ChatMessage `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	// 采样温度 [0, 2]，默认 1.0
	Temperature float32 `protobuf:"fixed32,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	// nucleus 采样概率质量 (0, 1]
	TopP float32 `protobuf:"fixed32,4,opt,name=top_p,json=topP,proto3" json:"top_p,omitempty"`
	// 生成候选数量 >= 1
	N int32 `protobuf:"varint,5,opt,name=n,proto3" json:"n,omitempty"`
	// 最大生成 token 数
	MaxTokens int32 `protobuf:"varint,6,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	// 停止序列（遇到即停止生成）
	Stop []string `protobuf:"bytes,7,rep,name=stop,proto3" json:"stop,omitempty"`
	// 存在惩罚 [-2, 2]
	PresencePenalty float32 `protobuf:"fixed32,8,opt,name=presence_penalty,json=presencePenalty,proto3" json:"presence_penalty,omitempty"`
	// 频率惩罚 [-2, 2]
	FrequencyPenalty float32 `protobuf:"fixed32,9,opt,name=frequency_penalty,json=frequencyPenalty,proto3" json:"frequency_penalty,omitempty"`
	// 用户标识（用于追踪）
	User string `protobuf:"bytes,10,opt,name=user,proto3" json:"user,omitempty"`
	// 可用工具列表
	Tools []*Tool `protobuf:"bytes,11,rep,name=tools,proto3" json:"tools,omitempty"`
	// 工具选择策略："none" / "auto" / "required" / 指定函数名
	ToolChoice string `protobuf:"bytes,12,opt,name=tool_choice,json=toolChoice,proto3" json:"tool_choice,omitempty"`
	// 响应格式控制
	ResponseFormat *ResponseFormat `protobuf:"bytes,13,opt,name=response_format,json=responseFormat,proto3" json:"response_format,omitempty"`
	// 随机数种子（可复现生成）
	Seed *int64 `protobuf:"varint,14,opt,name=seed,proto3,oneof" json:"seed,omitempty"`
	// 是否返回 logprobs
	Logprobs bool `protobuf:"varint,15,opt,name=logprobs,proto3" json:"logprobs,omitempty"`
	// 返回 top N 个 logprobs（需 logprobs=true）
	TopLogprobs *int32 `protobuf:"varint,16,opt,name=top_logprobs,json=topLogprobs,proto3,oneof" json:"top_logprobs,omitempty"`
	// 请求唯一 ID（平台侧生成，用于追踪链路）
	RequestId string `protobuf:"bytes,17,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// 是否启用思考/推理模式（enable_thinking）
	// 部分模型（如 Qwen3）可通过此字段在 chat template 中控制是否进入 thinking 模式
	EnableThinking *bool `protobuf:"varint,18,opt,name=enable_thinking,json=enableThinking,proto3,oneof" json:"enable_thinking,omitempty"`
	// OpenAI-standard reasoning effort level for thinking/reasoning models.
	// Values: "none", "minimal", "low", "medium", "high", "xhigh".
	// Takes priority over enable_thinking when both are set.
	// DeepNode engines use this for fine-grained thinking control.
	ReasoningEffort *string `protobuf:"bytes,19,opt,name=reasoning_effort,json=reasoningEffort,proto3,oneof" json:"reasoning_effort,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChatCompletionRequest) Reset() {
	*x = ChatCompletionRequest{}
	mi := &file_llm_infer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionRequest) ProtoMessage() {}

func (x *ChatCompletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_infer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionRequest.ProtoReflect.Descriptor instead.
func (*ChatCompletionRequest) Descriptor() ([]byte, []int) {
	return file_llm_infer_proto_rawDescGZIP(), []int{2}
}

func (x *ChatCompletionRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatCompletionRequest) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ChatCompletionRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *ChatCompletionRequest) GetTopP() float32 {
	if x != nil {
		return x.TopP
	}
	return 0
}

func (x *ChatCompletionRequest) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *ChatCompletionRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *ChatCompletionRequest) GetStop() []string {
	if x != nil {
		return x.Stop
	}
	return nil
}

func (x *ChatCompletionRequest) GetPresencePenalty() float32 {
	if x != nil {
		return x.PresencePenalty
	}
	return 0
}

func (x *ChatCompletionRequest) GetFrequencyPenalty() float32 {
	if x != nil {
		return x.FrequencyPenalty
	}
	return 0
}

func (x *ChatCompletionRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ChatCompletionRequest) GetTools() []*Tool {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *ChatCompletionRequest) GetToolChoice() string {
	if x != nil {
		return x.ToolChoice
	}
	return ""
}

func (x *ChatCompletionRequest) GetResponseFormat() *ResponseFormat {
	if x != nil {
		return x.ResponseFormat
	}
	return nil
}

func (x *ChatCompletionRequest) GetSeed() int64 {
	if x != nil && x.Seed != nil {
		return *x.Seed
	}
	return 0
}

func (x *ChatCompletionRequest) GetLogprobs() bool {
	if x != nil {
		return x.Logprobs
	}
	return false
}

func (x *ChatCompletionRequest) GetTopLogprobs() int32 {
	if x != nil && x.TopLogprobs != nil {
		return *x.TopLogprobs
	}
	return 0
}

func (x *ChatCompletionRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ChatCompletionRequest) GetEnableThinking() bool {
	if x != nil && x.EnableThinking != nil {
		return *x.EnableThinking
	}
	return false
}

func (x *ChatCompletionRequest) GetReasoningEffort() string {
	if x != nil && x.ReasoningEffort != nil {
		return *x.ReasoningEffort
	}
	return ""
}

type ChatMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "system" / "user" / "assistant" / "tool"
	Role string `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	// 文本内容（user/system/assistant 使用）
	Content *string `protobuf:"bytes,2,opt,name=content,proto3,oneof" json:"content,omitempty"`
	// 函数名（role=tool 时标识回复对应的函数）
	Name *string `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// assistant 发起的工具调用列表
	ToolCalls []*ToolCall `protobuf:"bytes,4,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	// role=tool 时，关联的 tool_call id
	ToolCallId *string `protobuf:"bytes,5,opt,name=tool_call_id,json=toolCallId,proto3,oneof" json:"tool_call_id,omitempty"`
	// 推理/思考内容（DeepSeek R1 的 reasoning_content / Qwen3 的 <think> 内容）
	// 仅 role=assistant 时有效
	ReasoningContent *string `protobuf:"bytes,6,opt,name=reasoning_content,json=reasoningContent,proto3,oneof" json:"reasoning_content,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_llm_infer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_llm_infer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_llm_infer_proto_rawDescGZIP(), []int{3}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *ChatMessage) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ChatMessage) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *ChatMessage) GetToolCallId() string {
	if x != nil && x.ToolCallId != nil {
		return *x.ToolCallId
	}
	return ""
}

func (x *ChatMessage) GetReasoningContent() string {
	if x != nil && x.ReasoningContent != nil {
		return *x.ReasoningContent
	}
	return ""
}

type Tool struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 固定为 "function"
	Type          string              `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Function      *FunctionDefinition `protobuf:"bytes,2,opt,name=function,proto3" json:"function,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tool) Reset() {
	*x = Tool{}
	mi := &file_llm_infer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool) ProtoMessage() {}

func (x *Tool) ProtoReflect() protoreflect.Message {
	mi := &file_llm_infer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool.ProtoReflect.Descriptor instead.
func (*Tool) Descriptor() ([]byte, []int) {
	return file_llm_infer_proto_rawDescGZIP(), []int{4}
}

func (x *Tool) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Tool) GetFunction() *FunctionDefinition {
	if x != nil {
		return x.Function
	}
	return nil
}

type FunctionDefinition struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// JSON Schema 字符串（parameters）
	Parameters    string `protobuf:"bytes,3,opt,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionDefinition) Reset() {
	*x = FunctionDefinition{}
	mi := &file_llm_infer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionDefinition) ProtoMessage() {}

func (x *FunctionDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_llm_infer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionDefinition.ProtoReflect.Descriptor instead.
func (*FunctionDefinition) Descriptor() ([]byte, []int) {
	return file_llm_infer_proto_rawDescGZIP(), []int{5}
}

func (x *FunctionDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionDefinition) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *FunctionDefinition) GetParameters() string {
	if x != nil {
		return x.Parameters
	}
	return ""
}

type ToolCall struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 固定为 "function"
	Type          string              `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Function      *FunctionCallDetail `protobuf:"bytes,3,opt,name=function,proto3" json:"function,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_llm_infer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_llm_infer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_llm_infer_proto_rawDescGZIP(), []int{6}
}

func (x *ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCall) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ToolCall) GetFunction() *FunctionCallDetail {
	if x != nil {
		return x.Function
	}
	return nil
}

type FunctionCallDetail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// JSON 字符串
	Arguments     string `protobuf:"bytes,2,opt,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionCallDetail) Reset() {
	*x = FunctionCallDetail{}
	mi := &file_llm_infer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionCallDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionCallDetail) ProtoMessage() {}

func (x *FunctionCallDetail) ProtoReflect() protoreflect.Message {
	mi := &file_llm_infer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionCallDetail.ProtoReflect.Descriptor instead.
func (*FunctionCallDetail) Descriptor() ([]byte, []int) {
	return file_llm_infer_proto_rawDescGZIP(), []int{7}
}

func (x *FunctionCallDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionCallDetail) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

type ResponseFormat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "text" / "json_object" / "json_schema"
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// 当 type=json_schema 时，存放 JSON Schema 字符串
	JsonSchema    *string `protobuf:"bytes,2,opt,name=json_schema,json=jsonSchema,proto3,oneof" json:"json_schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseFormat) Reset() {
	*x = ResponseFormat{}
	mi := &file_llm_infer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseFormat) ProtoMessage() {}

func (x *ResponseFormat) ProtoReflect() protoreflect.Message {
	mi := &file_llm_infer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseFormat.ProtoReflect.Descriptor instead.
func (*ResponseFormat) Descriptor() ([]byte, []int) {
	return file_llm_infer_proto_rawDescGZIP(), []int{8}
}

func (x *ResponseFormat) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResponseFormat) GetJsonSchema() string {
	if x != nil && x.JsonSchema != nil {
		return *x.JsonSchema
	}
	return ""
}

type TopLogprob struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Token   string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Logprob float32                `protobuf:"fixed32,2,opt,name=logprob,proto3" json:"logprob,omitempty"`
	// UTF-8 字节偏移（可选）
	Bytes         []int32 `protobuf:"varint,3,rep,packed,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopLogprob) Reset() {
	*x = TopLogprob{}
	mi := &file_llm_infer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopLogprob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopLogprob) ProtoMessage() {}

func (x *TopLogprob) ProtoReflect() protoreflect.Message {
	mi := &file_llm_infer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopLogprob.ProtoReflect.Descriptor instead.
func (*TopLogprob) Descriptor() ([]byte, []int) {
	return file_llm_infer_proto_rawDescGZIP(), []int{9}
}

func (x *TopLogprob) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TopLogprob) GetLogprob() float32 {
	if x != nil {
		return x.Logprob
	}
	return 0
}

func (x *TopLogprob) GetBytes() []int32 {
	if x != nil {
		return x.Bytes
	}
	return nil
}

type TokenLogprob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Logprob       float32                `protobuf:"fixed32,2,opt,name=logprob,proto3" json:"logprob,omitempty"`
	Bytes         []int32                `protobuf:"varint,3,rep,packed,name=bytes,proto3" json:"bytes,omitempty"`
	TopLogprobs   []*TopLogprob          `protobuf:"bytes,4,rep,name=top_logprobs,json=topLogprobs,proto3" json:"top_logprobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenLogprob) Reset() {
	*x = TokenLogprob{}
	mi := &file_llm_infer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenLogprob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenLogprob) ProtoMessage() {}

func (x *TokenLogprob) ProtoReflect() protoreflect.Message {
	mi := &file_llm_infer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenLogprob.ProtoReflect.Descriptor instead.
func (*TokenLogprob) Descriptor() ([]byte, []int) {
	return file_llm_infer_proto_rawDescGZIP(), []int{10}
}

func (x *TokenLogprob) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TokenLogprob) GetLogprob() float32 {
	if x != nil {
		return x.Logprob
	}
	return 0
}

func (x *TokenLogprob) GetBytes() []int32 {
	if x != nil {
		return x.Bytes
	}
	return nil
}

func (x *TokenLogprob) GetTopLogprobs() []*TopLogprob {
	if x != nil {
		return x.TopLogprobs
	}
	return nil
}

type ChoiceLogprobs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []*TokenLogprob        `protobuf:"bytes,1,rep,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChoiceLogprobs) Reset() {
	*x = ChoiceLogprobs{}
	mi := &file_llm_infer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChoiceLogprobs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChoiceLogprobs) ProtoMessage() {}

func (x *ChoiceLogprobs) ProtoReflect() protoreflect.Message {
	mi := &file_llm_infer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChoiceLogprobs.ProtoReflect.Descriptor instead.
func (*ChoiceLogprobs) Descriptor() ([]byte, []int) {
	return file_llm_infer_proto_rawDescGZIP(), []int{11}
}

func (x *ChoiceLogprobs) GetContent() []*TokenLogprob {
	if x != nil {
		return x.Content
	}
	return nil
}

// 对齐 OpenAI CompletionTokensDetails
type CompletionTokensDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 推理/思考阶段消耗的 token 数
	ReasoningTokens int32 `protobuf:"varint,1,opt,name=reasoning_tokens,json=reasoningTokens,proto3" json:"reasoning_tokens,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CompletionTokensDetails) Reset() {
	*x = CompletionTokensDetails{}
	mi := &file_llm_infer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionTokensDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionTokensDetails) ProtoMessage() {}

func (x *CompletionTokensDetails) ProtoReflect() protoreflect.Message {
	mi := &file_llm_infer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionTokensDetails.ProtoReflect.Descriptor instead.
func (*CompletionTokensDetails) Descriptor() ([]byte, []int) {
	return file_llm_infer_proto_rawDescGZIP(), []int{12}
}

func (x *CompletionTokensDetails) GetReasoningTokens() int32 {
	if x != nil {
		return x.ReasoningTokens
	}
	return 0
}

type Usage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens     int32                  `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int32                  `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	TotalTokens      int32                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	// 补全 token 的细分统计（reasoning_tokens 等）
	CompletionTokensDetails *CompletionTokensDetails `protobuf:"bytes,4,opt,name=completion_tokens_details,json=completionTokensDetails,proto3,oneof" json:"completion_tokens_details,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_llm_infer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_llm_infer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_llm_infer_proto_rawDescGZIP(), []int{13}
}

func (x *Usage) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *Usage) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *Usage) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *Usage) GetCompletionTokensDetails() *CompletionTokensDetails {
	if x != nil {
		return x.CompletionTokensDetails
	}
	return nil
}

type ChatCompletionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 固定 "chat.completion"
	Object            string    `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	Created           int64     `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Model             string    `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Choices           []*Choice `protobuf:"bytes,5,rep,name=choices,proto3" json:"choices,omitempty"`
	Usage             *Usage    `protobuf:"bytes,6,opt,name=usage,proto3" json:"usage,omitempty"`
	SystemFingerprint *string   `protobuf:"bytes,7,opt,name=system_fingerprint,json=systemFingerprint,proto3,oneof" json:"system_fingerprint,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ChatCompletionResponse) Reset() {
	*x = ChatCompletionResponse{}
	mi := &file_llm_infer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionResponse) ProtoMessage() {}

func (x *ChatCompletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_infer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionResponse.ProtoReflect.Descriptor instead.
func (*ChatCompletionResponse) Descriptor() ([]byte, []int) {
	return file_llm_infer_proto_rawDescGZIP(), []int{14}
}

func (x *ChatCompletionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatCompletionResponse) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *ChatCompletionResponse) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *ChatCompletionResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatCompletionResponse) GetChoices() []*Choice {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *ChatCompletionResponse) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *ChatCompletionResponse) GetSystemFingerprint() string {
	if x != nil && x.SystemFingerprint != nil {
		return *x.SystemFingerprint
	}
	return ""
}

type Choice struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Index   int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Message *ChatMessage           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// "stop" / "length" / "tool_calls" / "content_filter"
	FinishReason  string          `protobuf:"bytes,3,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	Logprobs      *ChoiceLogprobs `protobuf:"bytes,4,opt,name=logprobs,proto3,oneof" json:"logprobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Choice) Reset() {
	*x = Choice{}
	mi := &file_llm_infer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Choice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Choice) ProtoMessage() {}

func (x *Choice) ProtoReflect() protoreflect.Message {
	mi := &file_llm_infer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Choice.ProtoReflect.Descriptor instead.
func (*Choice) Descriptor() ([]byte, []int) {
	return file_llm_infer_proto_rawDescGZIP(), []int{15}
}

func (x *Choice) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Choice) GetMessage() *ChatMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Choice) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *Choice) GetLogprobs() *ChoiceLogprobs {
	if x != nil {
		return x.Logprobs
	}
	return nil
}

type ChatCompletionChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 固定 "chat.completion.chunk"
	Object  string         `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	Created int64          `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Model   string         `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Choices []*ChunkChoice `protobuf:"bytes,5,rep,name=choices,proto3" json:"choices,omitempty"`
	// 最后一个 chunk 携带 usage
	Usage             *Usage  `protobuf:"bytes,6,opt,name=usage,proto3,oneof" json:"usage,omitempty"`
	SystemFingerprint *string `protobuf:"bytes,7,opt,name=system_fingerprint,json=systemFingerprint,proto3,oneof" json:"system_fingerprint,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ChatCompletionChunk) Reset() {
	*x = ChatCompletionChunk{}
	mi := &file_llm_infer_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionChunk) ProtoMessage() {}

func (x *ChatCompletionChunk) ProtoReflect() protoreflect.Message {
	mi := &file_llm_infer_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionChunk.ProtoReflect.Descriptor instead.
func (*ChatCompletionChunk) Descriptor() ([]byte, []int) {
	return file_llm_infer_proto_rawDescGZIP(), []int{16}
}

func (x *ChatCompletionChunk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatCompletionChunk) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *ChatCompletionChunk) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *ChatCompletionChunk) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatCompletionChunk) GetChoices() []*ChunkChoice {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *ChatCompletionChunk) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *ChatCompletionChunk) GetSystemFingerprint() string {
	if x != nil && x.SystemFingerprint != nil {
		return *x.SystemFingerprint
	}
	return ""
}

type ChunkChoice struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Index int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Delta *ChatMessageDelta      `protobuf:"bytes,2,opt,name=delta,proto3" json:"delta,omitempty"`
	// 中间 chunk 为空，最后一个 chunk 携带 finish_reason
	FinishReason  *string         `protobuf:"bytes,3,opt,name=finish_reason,json=finishReason,proto3,oneof" json:"finish_reason,omitempty"`
	Logprobs      *ChoiceLogprobs `protobuf:"bytes,4,opt,name=logprobs,proto3,oneof" json:"logprobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkChoice) Reset() {
	*x = ChunkChoice{}
	mi := &file_llm_infer_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkChoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkChoice) ProtoMessage() {}

func (x *ChunkChoice) ProtoReflect() protoreflect.Message {
	mi := &file_llm_infer_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkChoice.ProtoReflect.Descriptor instead.
func (*ChunkChoice) Descriptor() ([]byte, []int) {
	return file_llm_infer_proto_rawDescGZIP(), []int{17}
}

func (x *ChunkChoice) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ChunkChoice) GetDelta() *ChatMessageDelta {
	if x != nil {
		return x.Delta
	}
	return nil
}

func (x *ChunkChoice) GetFinishReason() string {
	if x != nil && x.FinishReason != nil {
		return *x.FinishReason
	}
	return ""
}

func (x *ChunkChoice) GetLogprobs() *ChoiceLogprobs {
	if x != nil {
		return x.Logprobs
	}
	return nil
}

// 流式 delta（每个字段都是可选的增量片段）
type ChatMessageDelta struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Role      *string                `protobuf:"bytes,1,opt,name=role,proto3,oneof" json:"role,omitempty"`
	Content   *string                `protobuf:"bytes,2,opt,name=content,proto3,oneof" json:"content,omitempty"`
	ToolCalls []*ToolCall            `protobuf:"bytes,3,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	// 推理/思考内容增量（流式输出 reasoning_content）
	ReasoningContent *string `protobuf:"bytes,4,opt,name=reasoning_content,json=reasoningContent,proto3,oneof" json:"reasoning_content,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChatMessageDelta) Reset() {
	*x = ChatMessageDelta{}
	mi := &file_llm_infer_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessageDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessageDelta) ProtoMessage() {}

func (x *ChatMessageDelta) ProtoReflect() protoreflect.Message {
	mi := &file_llm_infer_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessageDelta.ProtoReflect.Descriptor instead.
func (*ChatMessageDelta) Descriptor() ([]byte, []int) {
	return file_llm_infer_proto_rawDescGZIP(), []int{18}
}

func (x *ChatMessageDelta) GetRole() string {
	if x != nil && x.Role != nil {
		return *x.Role
	}
	return ""
}

func (x *ChatMessageDelta) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *ChatMessageDelta) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *ChatMessageDelta) GetReasoningContent() string {
	if x != nil && x.ReasoningContent != nil {
		return *x.ReasoningContent
	}
	return ""
}

var File_llm_infer_proto protoreflect.FileDescriptor

const file_llm_infer_proto_rawDesc = "" +
	"\n" +
	"\x0fllm_infer.proto\x12\x0fdeeppool.llm.v1\"\x0f\n" +
	"\rHealthRequest\"_\n" +
	"\x0eHealthResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x80\x06\n" +
	"\x15ChatCompletionRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x128\n" +
	"\bmessages\x18\x02 \x03(\v2\x1c.deeppool.llm.v1.ChatMessageR\bmessages\x12 \n" +
	"\vtemperature\x18\x03 \x01(\x02R\vtemperature\x12\x13\n" +
	"\x05top_p\x18\x04 \x01(\x02R\x04topP\x12\f\n" +
	"\x01n\x18\x05 \x01(\x05R\x01n\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x06 \x01(\x05R\tmaxTokens\x12\x12\n" +
	"\x04stop\x18\a \x03(\tR\x04stop\x12)\n" +
	"\x10presence_penalty\x18\b \x01(\x02R\x0fpresencePenalty\x12+\n" +
	"\x11frequency_penalty\x18\t \x01(\x02R\x10frequencyPenalty\x12\x12\n" +
	"\x04user\x18\n" +
	" \x01(\tR\x04user\x12+\n" +
	"\x05tools\x18\v \x03(\v2\x15.deeppool.llm.v1.ToolR\x05tools\x12\x1f\n" +
	"\vtool_choice\x18\f \x01(\tR\n" +
	"toolChoice\x12H\n" +
	"\x0fresponse_format\x18\r \x01(\v2\x1f.deeppool.llm.v1.ResponseFormatR\x0eresponseFormat\x12\x17\n" +
	"\x04seed\x18\x0e \x01(\x03H\x00R\x04seed\x88\x01\x01\x12\x1a\n" +
	"\blogprobs\x18\x0f \x01(\bR\blogprobs\x12&\n" +
	"\ftop_logprobs\x18\x10 \x01(\x05H\x01R\vtopLogprobs\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"request_id\x18\x11 \x01(\tR\trequestId\x12,\n" +
	"\x0fenable_thinking\x18\x12 \x01(\bH\x02R\x0eenableThinking\x88\x01\x01\x12.\n" +
	"\x10reasoning_effort\x18\x13 \x01(\tH\x03R\x0freasoningEffort\x88\x01\x01B\a\n" +
	"\x05_seedB\x0f\n" +
	"\r_top_logprobsB\x12\n" +
	"\x10_enable_thinkingB\x13\n" +
	"\x11_reasoning_effort\"\xa8\x02\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x1d\n" +
	"\acontent\x18\x02 \x01(\tH\x00R\acontent\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x01R\x04name\x88\x01\x01\x128\n" +
	"\n" +
	"tool_calls\x18\x04 \x03(\v2\x19.deeppool.llm.v1.ToolCallR\ttoolCalls\x12%\n" +
	"\ftool_call_id\x18\x05 \x01(\tH\x02R\n" +
	"toolCallId\x88\x01\x01\x120\n" +
	"\x11reasoning_content\x18\x06 \x01(\tH\x03R\x10reasoningContent\x88\x01\x01B\n" +
	"\n" +
	"\b_contentB\a\n" +
	"\x05_nameB\x0f\n" +
	"\r_tool_call_idB\x14\n" +
	"\x12_reasoning_content\"[\n" +
	"\x04Tool\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12?\n" +
	"\bfunction\x18\x02 \x01(\v2#.deeppool.llm.v1.FunctionDefinitionR\bfunction\"\x7f\n" +
	"\x12FunctionDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"parameters\x18\x03 \x01(\tR\n" +
	"parametersB\x0e\n" +
	"\f_description\"o\n" +
	"\bToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12?\n" +
	"\bfunction\x18\x03 \x01(\v2#.deeppool.llm.v1.FunctionCallDetailR\bfunction\"F\n" +
	"\x12FunctionCallDetail\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\targuments\x18\x02 \x01(\tR\targuments\"Z\n" +
	"\x0eResponseFormat\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12$\n" +
	"\vjson_schema\x18\x02 \x01(\tH\x00R\n" +
	"jsonSchema\x88\x01\x01B\x0e\n" +
	"\f_json_schema\"R\n" +
	"\n" +
	"TopLogprob\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x18\n" +
	"\alogprob\x18\x02 \x01(\x02R\alogprob\x12\x14\n" +
	"\x05bytes\x18\x03 \x03(\x05R\x05bytes\"\x94\x01\n" +
	"\fTokenLogprob\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x18\n" +
	"\alogprob\x18\x02 \x01(\x02R\alogprob\x12\x14\n" +
	"\x05bytes\x18\x03 \x03(\x05R\x05bytes\x12>\n" +
	"\ftop_logprobs\x18\x04 \x03(\v2\x1b.deeppool.llm.v1.TopLogprobR\vtopLogprobs\"I\n" +
	"\x0eChoiceLogprobs\x127\n" +
	"\acontent\x18\x01 \x03(\v2\x1d.deeppool.llm.v1.TokenLogprobR\acontent\"D\n" +
	"\x17CompletionTokensDetails\x12)\n" +
	"\x10reasoning_tokens\x18\x01 \x01(\x05R\x0freasoningTokens\"\x85\x02\n" +
	"\x05Usage\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x02 \x01(\x05R\x10completionTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x05R\vtotalTokens\x12i\n" +
	"\x19completion_tokens_details\x18\x04 \x01(\v2(.deeppool.llm.v1.CompletionTokensDetailsH\x00R\x17completionTokensDetails\x88\x01\x01B\x1c\n" +
	"\x1a_completion_tokens_details\"\x9c\x02\n" +
	"\x16ChatCompletionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06object\x18\x02 \x01(\tR\x06object\x12\x18\n" +
	"\acreated\x18\x03 \x01(\x03R\acreated\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x121\n" +
	"\achoices\x18\x05 \x03(\v2\x17.deeppool.llm.v1.ChoiceR\achoices\x12,\n" +
	"\x05usage\x18\x06 \x01(\v2\x16.deeppool.llm.v1.UsageR\x05usage\x122\n" +
	"\x12system_fingerprint\x18\a \x01(\tH\x00R\x11systemFingerprint\x88\x01\x01B\x15\n" +
	"\x13_system_fingerprint\"\xca\x01\n" +
	"\x06Choice\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x126\n" +
	"\amessage\x18\x02 \x01(\v2\x1c.deeppool.llm.v1.ChatMessageR\amessage\x12#\n" +
	"\rfinish_reason\x18\x03 \x01(\tR\ffinishReason\x12@\n" +
	"\blogprobs\x18\x04 \x01(\v2\x1f.deeppool.llm.v1.ChoiceLogprobsH\x00R\blogprobs\x88\x01\x01B\v\n" +
	"\t_logprobs\"\xad\x02\n" +
	"\x13ChatCompletionChunk\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06object\x18\x02 \x01(\tR\x06object\x12\x18\n" +
	"\acreated\x18\x03 \x01(\x03R\acreated\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x126\n" +
	"\achoices\x18\x05 \x03(\v2\x1c.deeppool.llm.v1.ChunkChoiceR\achoices\x121\n" +
	"\x05usage\x18\x06 \x01(\v2\x16.deeppool.llm.v1.UsageH\x00R\x05usage\x88\x01\x01\x122\n" +
	"\x12system_fingerprint\x18\a \x01(\tH\x01R\x11systemFingerprint\x88\x01\x01B\b\n" +
	"\x06_usageB\x15\n" +
	"\x13_system_fingerprint\"\xe7\x01\n" +
	"\vChunkChoice\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x127\n" +
	"\x05delta\x18\x02 \x01(\v2!.deeppool.llm.v1.ChatMessageDeltaR\x05delta\x12(\n" +
	"\rfinish_reason\x18\x03 \x01(\tH\x00R\ffinishReason\x88\x01\x01\x12@\n" +
	"\blogprobs\x18\x04 \x01(\v2\x1f.deeppool.llm.v1.ChoiceLogprobsH\x01R\blogprobs\x88\x01\x01B\x10\n" +
	"\x0e_finish_reasonB\v\n" +
	"\t_logprobs\"\xe1\x01\n" +
	"\x10ChatMessageDelta\x12\x17\n" +
	"\x04role\x18\x01 \x01(\tH\x00R\x04role\x88\x01\x01\x12\x1d\n" +
	"\acontent\x18\x02 \x01(\tH\x01R\acontent\x88\x01\x01\x128\n" +
	"\n" +
	"tool_calls\x18\x03 \x03(\v2\x19.deeppool.llm.v1.ToolCallR\ttoolCalls\x120\n" +
	"\x11reasoning_content\x18\x04 \x01(\tH\x02R\x10reasoningContent\x88\x01\x01B\a\n" +
	"\x05_roleB\n" +
	"\n" +
	"\b_contentB\x14\n" +
	"\x12_reasoning_content2\xa7\x02\n" +
	"\x0fLLMInferService\x12I\n" +
	"\x06Health\x12\x1e.deeppool.llm.v1.HealthRequest\x1a\x1f.deeppool.llm.v1.HealthResponse\x12a\n" +
	"\x0eChatCompletion\x12&.deeppool.llm.v1.ChatCompletionRequest\x1a'.deeppool.llm.v1.ChatCompletionResponse\x12f\n" +
	"\x14ChatCompletionStream\x12&.deeppool.llm.v1.ChatCompletionRequest\x1a$.deeppool.llm.v1.ChatCompletionChunk0\x01B\"Z deeppool/libs/proto/llm/v1;llmv1b\x06proto3"

var (
	file_llm_infer_proto_rawDescOnce sync.Once
	file_llm_infer_proto_rawDescData []byte
)

func file_llm_infer_proto_rawDescGZIP() []byte {
	file_llm_infer_proto_rawDescOnce.Do(func() {
		file_llm_infer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llm_infer_proto_rawDesc), len(file_llm_infer_proto_rawDesc)))
	})
	return file_llm_infer_proto_rawDescData
}

var file_llm_infer_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_llm_infer_proto_goTypes = []any{
	(*HealthRequest)(nil),           // 0: deeppool.llm.v1.HealthRequest
	(*HealthResponse)(nil),          // 1: deeppool.llm.v1.HealthResponse
	(*ChatCompletionRequest)(nil),   // 2: deeppool.llm.v1.ChatCompletionRequest
	(*ChatMessage)(nil),             // 3: deeppool.llm.v1.ChatMessage
	(*Tool)(nil),                    // 4: deeppool.llm.v1.Tool
	(*FunctionDefinition)(nil),      // 5: deeppool.llm.v1.FunctionDefinition
	(*ToolCall)(nil),                // 6: deeppool.llm.v1.ToolCall
	(*FunctionCallDetail)(nil),      // 7: deeppool.llm.v1.FunctionCallDetail
	(*ResponseFormat)(nil),          // 8: deeppool.llm.v1.ResponseFormat
	(*TopLogprob)(nil),              // 9: deeppool.llm.v1.TopLogprob
	(*TokenLogprob)(nil),            // 10: deeppool.llm.v1.TokenLogprob
	(*ChoiceLogprobs)(nil),          // 11: deeppool.llm.v1.ChoiceLogprobs
	(*CompletionTokensDetails)(nil), // 12: deeppool.llm.v1.CompletionTokensDetails
	(*Usage)(nil),                   // 13: deeppool.llm.v1.Usage
	(*ChatCompletionResponse)(nil),  // 14: deeppool.llm.v1.ChatCompletionResponse
	(*Choice)(nil),                  // 15: deeppool.llm.v1.Choice
	(*ChatCompletionChunk)(nil),     // 16: deeppool.llm.v1.ChatCompletionChunk
	(*ChunkChoice)(nil),             // 17: deeppool.llm.v1.ChunkChoice
	(*ChatMessageDelta)(nil),        // 18: deeppool.llm.v1.ChatMessageDelta
}
var file_llm_infer_proto_depIdxs = []int32{
	3,  // 0: deeppool.llm.v1.ChatCompletionRequest.messages:type_name -> deeppool.llm.v1.ChatMessage
	4,  // 1: deeppool.llm.v1.ChatCompletionRequest.tools:type_name -> deeppool.llm.v1.Tool
	8,  // 2: deeppool.llm.v1.ChatCompletionRequest.response_format:type_name -> deeppool.llm.v1.ResponseFormat
	6,  // 3: deeppool.llm.v1.ChatMessage.tool_calls:type_name -> deeppool.llm.v1.ToolCall
	5,  // 4: deeppool.llm.v1.Tool.function:type_name -> deeppool.llm.v1.FunctionDefinition
	7,  // 5: deeppool.llm.v1.ToolCall.function:type_name -> deeppool.llm.v1.FunctionCallDetail
	9,  // 6: deeppool.llm.v1.TokenLogprob.top_logprobs:type_name -> deeppool.llm.v1.TopLogprob
	10, // 7: deeppool.llm.v1.ChoiceLogprobs.content:type_name -> deeppool.llm.v1.TokenLogprob
	12, // 8: deeppool.llm.v1.Usage.completion_tokens_details:type_name -> deeppool.llm.v1.CompletionTokensDetails
	15, // 9: deeppool.llm.v1.ChatCompletionResponse.choices:type_name -> deeppool.llm.v1.Choice
	13, // 10: deeppool.llm.v1.ChatCompletionResponse.usage:type_name -> deeppool.llm.v1.Usage
	3,  // 11: deeppool.llm.v1.Choice.message:type_name -> deeppool.llm.v1.ChatMessage
	11, // 12: deeppool.llm.v1.Choice.logprobs:type_name -> deeppool.llm.v1.ChoiceLogprobs
	17, // 13: deeppool.llm.v1.ChatCompletionChunk.choices:type_name -> deeppool.llm.v1.ChunkChoice
	13, // 14: deeppool.llm.v1.ChatCompletionChunk.usage:type_name -> deeppool.llm.v1.Usage
	18, // 15: deeppool.llm.v1.ChunkChoice.delta:type_name -> deeppool.llm.v1.ChatMessageDelta
	11, // 16: deeppool.llm.v1.ChunkChoice.logprobs:type_name -> deeppool.llm.v1.ChoiceLogprobs
	6,  // 17: deeppool.llm.v1.ChatMessageDelta.tool_calls:type_name -> deeppool.llm.v1.ToolCall
	0,  // 18: deeppool.llm.v1.LLMInferService.Health:input_type -> deeppool.llm.v1.HealthRequest
	2,  // 19: deeppool.llm.v1.LLMInferService.ChatCompletion:input_type -> deeppool.llm.v1.ChatCompletionRequest
	2,  // 20: deeppool.llm.v1.LLMInferService.ChatCompletionStream:input_type -> deeppool.llm.v1.ChatCompletionRequest
	1,  // 21: deeppool.llm.v1.LLMInferService.Health:output_type -> deeppool.llm.v1.HealthResponse
	14, // 22: deeppool.llm.v1.LLMInferService.ChatCompletion:output_type -> deeppool.llm.v1.ChatCompletionResponse
	16, // 23: deeppool.llm.v1.LLMInferService.ChatCompletionStream:output_type -> deeppool.llm.v1.ChatCompletionChunk
	21, // [21:24] is the sub-list for method output_type
	18, // [18:21] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_llm_infer_proto_init() }
func file_llm_infer_proto_init() {
	if File_llm_infer_proto != nil {
		return
	}
	file_llm_infer_proto_msgTypes[2].OneofWrappers = []any{}
	file_llm_infer_proto_msgTypes[3].OneofWrappers = []any{}
	file_llm_infer_proto_msgTypes[5].OneofWrappers = []any{}
	file_llm_infer_proto_msgTypes[8].OneofWrappers = []any{}
	file_llm_infer_proto_msgTypes[13].OneofWrappers = []any{}
	file_llm_infer_proto_msgTypes[14].OneofWrappers = []any{}
	file_llm_infer_proto_msgTypes[15].OneofWrappers = []any{}
	file_llm_infer_proto_msgTypes[16].OneofWrappers = []any{}
	file_llm_infer_proto_msgTypes[17].OneofWrappers = []any{}
	file_llm_infer_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llm_infer_proto_rawDesc), len(file_llm_infer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_llm_infer_proto_goTypes,
		DependencyIndexes: file_llm_infer_proto_depIdxs,
		MessageInfos:      file_llm_infer_proto_msgTypes,
	}.Build()
	File_llm_infer_proto = out.File
	file_llm_infer_proto_goTypes = nil
	file_llm_infer_proto_depIdxs = nil
}
