// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: llm_infer.proto

package llmv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LLMInferService_Health_FullMethodName               = "/deeppool.llm.v1.LLMInferService/Health"
	LLMInferService_ChatCompletion_FullMethodName       = "/deeppool.llm.v1.LLMInferService/ChatCompletion"
	LLMInferService_ChatCompletionStream_FullMethodName = "/deeppool.llm.v1.LLMInferService/ChatCompletionStream"
)

// LLMInferServiceClient is the client API for LLMInferService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ─────────────────────────────────────────────────
// LLMInferService — 严格对齐 OpenAI Chat Completions API
// 支持: 非流式 / 流式 / tools / response_format / logprobs / n
// 兼容: DeepSeek R1 (reasoning_content) / Qwen3 (think) 等模型
// ─────────────────────────────────────────────────
type LLMInferServiceClient interface {
	// 健康检查
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Chat Completions（非流式）
	ChatCompletion(ctx context.Context, in *ChatCompletionRequest, opts ...grpc.CallOption) (*ChatCompletionResponse, error)
	// Chat Completions（服务端流式）
	ChatCompletionStream(ctx context.Context, in *ChatCompletionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatCompletionChunk], error)
}

type lLMInferServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLLMInferServiceClient(cc grpc.ClientConnInterface) LLMInferServiceClient {
	return &lLMInferServiceClient{cc}
}

func (c *lLMInferServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, LLMInferService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMInferServiceClient) ChatCompletion(ctx context.Context, in *ChatCompletionRequest, opts ...grpc.CallOption) (*ChatCompletionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatCompletionResponse)
	err := c.cc.Invoke(ctx, LLMInferService_ChatCompletion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMInferServiceClient) ChatCompletionStream(ctx context.Context, in *ChatCompletionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatCompletionChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LLMInferService_ServiceDesc.Streams[0], LLMInferService_ChatCompletionStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatCompletionRequest, ChatCompletionChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LLMInferService_ChatCompletionStreamClient = grpc.ServerStreamingClient[ChatCompletionChunk]

// LLMInferServiceServer is the server API for LLMInferService service.
// All implementations must embed UnimplementedLLMInferServiceServer
// for forward compatibility.
//
// ─────────────────────────────────────────────────
// LLMInferService — 严格对齐 OpenAI Chat Completions API
// 支持: 非流式 / 流式 / tools / response_format / logprobs / n
// 兼容: DeepSeek R1 (reasoning_content) / Qwen3 (think) 等模型
// ─────────────────────────────────────────────────
type LLMInferServiceServer interface {
	// 健康检查
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// Chat Completions（非流式）
	ChatCompletion(context.Context, *ChatCompletionRequest) (*ChatCompletionResponse, error)
	// Chat Completions（服务端流式）
	ChatCompletionStream(*ChatCompletionRequest, grpc.ServerStreamingServer[ChatCompletionChunk]) error
	mustEmbedUnimplementedLLMInferServiceServer()
}

// UnimplementedLLMInferServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLLMInferServiceServer struct{}

func (UnimplementedLLMInferServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedLLMInferServiceServer) ChatCompletion(context.Context, *ChatCompletionRequest) (*ChatCompletionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChatCompletion not implemented")
}
func (UnimplementedLLMInferServiceServer) ChatCompletionStream(*ChatCompletionRequest, grpc.ServerStreamingServer[ChatCompletionChunk]) error {
	return status.Error(codes.Unimplemented, "method ChatCompletionStream not implemented")
}
func (UnimplementedLLMInferServiceServer) mustEmbedUnimplementedLLMInferServiceServer() {}
func (UnimplementedLLMInferServiceServer) testEmbeddedByValue()                         {}

// UnsafeLLMInferServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LLMInferServiceServer will
// result in compilation errors.
type UnsafeLLMInferServiceServer interface {
	mustEmbedUnimplementedLLMInferServiceServer()
}

func RegisterLLMInferServiceServer(s grpc.ServiceRegistrar, srv LLMInferServiceServer) {
	// If the following call panics, it indicates UnimplementedLLMInferServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LLMInferService_ServiceDesc, srv)
}

func _LLMInferService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMInferServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMInferService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMInferServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMInferService_ChatCompletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatCompletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMInferServiceServer).ChatCompletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMInferService_ChatCompletion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMInferServiceServer).ChatCompletion(ctx, req.(*ChatCompletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMInferService_ChatCompletionStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatCompletionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LLMInferServiceServer).ChatCompletionStream(m, &grpc.GenericServerStream[ChatCompletionRequest, ChatCompletionChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LLMInferService_ChatCompletionStreamServer = grpc.ServerStreamingServer[ChatCompletionChunk]

// LLMInferService_ServiceDesc is the grpc.ServiceDesc for LLMInferService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LLMInferService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "deeppool.llm.v1.LLMInferService",
	HandlerType: (*LLMInferServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _LLMInferService_Health_Handler,
		},
		{
			MethodName: "ChatCompletion",
			Handler:    _LLMInferService_ChatCompletion_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChatCompletionStream",
			Handler:       _LLMInferService_ChatCompletionStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "llm_infer.proto",
}
